<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Damian Vicente Cespedes">

<title>Trabajopractico.N.2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="2.practico_files/libs/clipboard/clipboard.min.js"></script>
<script src="2.practico_files/libs/quarto-html/quarto.js"></script>
<script src="2.practico_files/libs/quarto-html/popper.min.js"></script>
<script src="2.practico_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2.practico_files/libs/quarto-html/anchor.min.js"></script>
<link href="2.practico_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2.practico_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2.practico_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2.practico_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2.practico_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajopractico.N.2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Damian Vicente Cespedes </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="confianza-en-la-institucionalidad-politica-en-la-población-joven-de-entre-18-a-30-años" class="level2">
<h2 class="anchored" data-anchor-id="confianza-en-la-institucionalidad-politica-en-la-población-joven-de-entre-18-a-30-años">“Confianza en la institucionalidad politica en la población joven de entre 18 a 30 años”</h2>
<section id="introducción" class="level4">
<h4 class="anchored" data-anchor-id="introducción">Introducción</h4>
<p>Durante las últimas décadas, en latinoamérica se ha tendido a centrar el foco investigativo en torno a diferentes tipos de fenómenos sociales subyacentes. Esto se debe a que durante este último tiempo, el continente se ha caracterizado por la irrupción de diversas efervescencias en ámbitos sociales, políticos y económicos de gran magnitud. En esa línea, contextualmente, Chile representa un caso particular en donde, a partir del 18 de Octubre de 2019 se constituyó un punto de inflexión en la historia política y social del país. En aquella ocasión, los ciudadanos salieron a las calles de manera disgustada para exigir un sinnúmero de reformas sociales en materias como la salud, pensiones, educación, entre otras. Este suceso tomó forma clara a tal punto que llegó a convertirse en una suerte de llamada de atención para muchos sujetos del tapete político, quienes fueron interpelados críticamente debido a la mala interpretación por parte de ellos hacia las exigencias que demandaba la ciudadanía. Un descontento social que venía gestándose hacía varios años antes y que se exteriorizo mediante multitudinarias manifestaciones nunca antes vistas en aquel entonces.</p>
<p>En ese sentido, una de las grandes dificultades que enfrentamos como comunidad latina hace referencia a un progresivo incremento de desconfianza a la hora de hablar de la relación que logran establecer los actores políticos, quienes están al mando de la sociedad, con los mismos ciudadanos <span class="citation" data-cites="marchantsalamanca2021">(<a href="#ref-marchantsalamanca2021" role="doc-biblioref">Marchant Salamanca 2021</a>)</span>. En el caso Chileno, esto queda especialmente contrastado con hallazgos anteriores expuestos por <span class="citation" data-cites="moralesquiroga2008">Morales Quiroga (<a href="#ref-moralesquiroga2008" role="doc-biblioref">2008</a>)</span>, quien indaga en la relación entre la democracia y la confianza institucional, obteniendo como resultado una representación de insatisfacción y descontento por parte de la ciudadanía con algunos organismo del andamiaje democrático. Con el tiempo, se evidencia una clara reducción en la confianza institucional, que en ese entonces afectaba principalmente a organismos como el Gobierno, el Congreso y los partidos políticos <span class="citation" data-cites="moralesquiroga2020">(<a href="#ref-moralesquiroga2020" role="doc-biblioref">Morales Quiroga 2020</a>)</span>. Es decir,&nbsp;gran parte de la institucionalidad política representativa de la sociedad.</p>
<p>Para autores como <span class="citation" data-cites="laso2010">Laso (<a href="#ref-laso2010" role="doc-biblioref">2010</a>)</span>, la confianza institucional se asocia con la concepción de riesgo, entendiendo como puede uno generar (influir) y provocar cambios en los “niveles” subjetivos de confianza, ya sea disminuyéndolos o aumentándolos. El autor formula interesantes ideas al respecto, sugiriendo que el concepto en cuestión tendría dos niveles: las palabras y los actos. Según esta perspectiva, entonces la confianza se desarrolla cuando haya coincidencia entre ambas posturas, pero se perdería en cuanto exista discordancia en cuanto tal (2010). Bajo esta línea argumentativa, consideraremos que la confianza institucional es una dimensión que abarca la coincidencia en la coherencia que tengan los actos y palabras por parte de las instituciones políticas, así como de los actores involucrados que forman parte de aquel organismo social. Por tanto, lo anterior nos permite suponer que cuando haya una discrepancia entre lo dicho y lo hecho, ya sea por una mentira o un comportamiento inconsecuente, esto generará falta de credibilidad y, por consiguiente, la pérdida de confianza en las instituciones políticas mencionadas.</p>
<p>Este mismo autor, <span class="citation" data-cites="laso2010">(<a href="#ref-laso2010" role="doc-biblioref">Laso 2010</a>)</span>, además propone que la confianza en una sociedad con óptima funcionalidad de las instituciones ayudaría a reducir la complejidad y el desorden existentes en algunos ámbitos. Esto nos permite adentrarnos en la idea de que una sociedad en la cual prime la idea de desconfianza esta será una sociedad marcada por el desorden y eventuales crisis económicas, políticas y sociales. Es de importancia mencionar que, a título de Laso, la confianza, restringida al ámbito humano (es decir a las relaciones entre personas, individuos o instituciones), no siempre será recíproca, ya que estas están determinadas por las conductas anteriores de estos. Esto quiere decir que en una sociedad donde cierta parte de los individuos que tienen cargos políticos desempeñan funciones en base a malas prácticas que quebrantan a la comunidad, precisamente allí, es sumamente importante que las políticas públicas que se promuevan giren en torno a la transparencia. Pues la importancia de la confianza institucional es fundamental para el funcionamiento de un régimen político y la estabilidad de una nación.</p>
<p>Por su parte, autores como <span class="citation" data-cites="riffo2019">(<a href="#ref-riffo2019" role="doc-biblioref">Riffo et al. 2019</a>)</span> expresan que existe una factor importante en relación con una gran preponderancia de la variable que ya hemos mencionado con anterioridad, es decir, la confianza institucional, en concordancia con lo que vendría siendo el capital social. El autor principalmente refiere a que esta interrelación de conceptos son aspectos que deben de ser fundamentales para las organizaciones democráticas, pudiendo así lograr tener la factibilidad de mejorar el fortalecimiento en la eficacia de la representación política de las sociedades. Desde esta perspectiva, aquello quiere decir que se concibe a la confianza institucional como una especie de versificación de la cohesión social dentro de la colectividad.</p>
<p>En esa línea, el contexto político Chileno ya mencionado deja a entrever un relativo aumento hacia la presentación de una situación sociopolítica compleja en cuanto a una relación de amplia distancia de desconfianza en una amplia distancia por parte de los ciudadanos, hacia gran parte de los sectores políticos, ya sea de diversa ubicación en el entorno ideológico izquierda/derecha, sea el Gobierno de turno, Partidos Políticos y Congreso Nacional. En cierta medida, esto nos lleva a plantear la hipótesis central que encamina este trabajo, la cual refiere a que actualmente estamos frente a la presencia de una crisis de corte institucional en la gubernamentalidad política del país, manifestada en una en cuanto a una aparente baja progresiva en los estándares de confianza por parte de la ciudadanía frente a estos organismos políticos. En concordancia con eso, la pregunta que guía este estudio es si las capacidades institucionales de los agentes políticos inciden en la confianza política que las personas depositan en ellos y, de existir tal influencia, cómo es dicha relación. Por tanto el argumento principal como ya ha sido sostenido con anterioridad refiere a que los actuales organismo políticos más importantes para la sociedad chilena (Gobierno, Partidos Políticos y Congresos) se encuentran en una crisis de desconfianza institucional por parte de la ciudadanía. Desde alli, intentaremos realizar un a segmentación por sexo, y además también interemos realiza un filtro por rangos etarios de la población más joven de adultos, que para efectos de este trabajo ronda entre los 18 a 30 años.</p>
<p>Para efectros de la presenta investigacion, recurrimos a una base de datos correspondiente a obtenida a traves de un estudio longitudinal realizado por el COES en Chile entre los años 2016 y 2022. Fundamentalemnte, emplearemos los datos de ELSOC_2016_2022 con el fin de observar como se plasma la relación de confianza de la ciudadania para con los entes politicos que estan al mando de la sociedad.</p>
</section>
<section id="trabajo-en-r" class="level3">
<h3 class="anchored" data-anchor-id="trabajo-en-r">Trabajo en R</h3>
<section id="ajustes-iniciales" class="level5">
<h5 class="anchored" data-anchor-id="ajustes-iniciales">Ajustes iniciales</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())       <span class="co"># borrar todos los objetos en el espacio de trabajo</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>) <span class="co"># valores sin notación científica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="cargar-paquetes" class="level3">
<h3 class="anchored" data-anchor-id="cargar-paquetes">Cargar paquetes</h3>
<p>Para la realización del presente estudio, emplearemos la utilización de Rstudio para poder visualizar y trabajar con los datos, en donde trabajaremos mediante un R script. Como primer paso debemos cargar una serie de paquetes que nos permitan analizar y utilizar lo que necesitamos para fines investigativos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sjlabelled,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>               dplyr, <span class="co">#Manipulacion de datos</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>               stargazer, <span class="co">#Tablas</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>               sjmisc, <span class="co"># Tablas</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>               summarytools, <span class="co"># Tablas</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>               kableExtra, <span class="co">#Tablas</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>               sjPlot, <span class="co">#Tablas y gráficos</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>               corrplot, <span class="co"># Correlaciones</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>               sessioninfo, <span class="co"># Información de la sesión de trabajo</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>               ggplot2) <span class="co"># Para la mayoría de los gráficos</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.1
✔ readr     2.1.5     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ tibble::add_case()       masks sjmisc::add_case()
✖ forcats::as_factor()     masks sjlabelled::as_factor()
✖ ggplot2::as_label()      masks dplyr::as_label(), sjlabelled::as_label()
✖ dplyr::filter()          masks stats::filter()
✖ kableExtra::group_rows() masks dplyr::group_rows()
✖ purrr::is_empty()        masks sjmisc::is_empty()
✖ dplyr::lag()             masks stats::lag()
✖ tidyr::replace_na()      masks sjmisc::replace_na()
✖ tibble::view()           masks summarytools::view()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"table1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'table1' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'table1'

The following objects are masked from 'package:summarytools':

    label, label&lt;-

The following objects are masked from 'package:base':

    units, units&lt;-</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"psych"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'psych' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'

The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"haven"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'haven' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'haven'

The following objects are masked from 'package:sjlabelled':

    as_factor, read_sas, read_spss, read_stata, write_sas, zap_labels</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"sjmisc"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"lm.beta"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lm.beta' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"Hmisc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'Hmisc' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Hmisc'

The following object is masked from 'package:psych':

    describe

The following objects are masked from 'package:table1':

    label, label&lt;-, units

The following objects are masked from 'package:summarytools':

    label, label&lt;-

The following object is masked from 'package:sjmisc':

    %nin%

The following objects are masked from 'package:dplyr':

    src, summarize

The following objects are masked from 'package:base':

    format.pval, units</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"PerformanceAnalytics"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'PerformanceAnalytics' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: xts
Loading required package: zoo

Attaching package: 'zoo'

The following objects are masked from 'package:base':

    as.Date, as.Date.numeric


Attaching package: 'xts'

The following objects are masked from 'package:dplyr':

    first, last


Attaching package: 'PerformanceAnalytics'

The following object is masked from 'package:graphics':

    legend</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"sjPlot"</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"texreg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'texreg' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Version:  1.39.3
Date:     2023-11-09
Author:   Philip Leifeld (University of Essex)

Consider submitting praise using the praise or praise_interactive functions.
Please cite the JSS article in your publications -- see citation("texreg").

Attaching package: 'texreg'

The following object is masked from 'package:tidyr':

    extract</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"car"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'carData' was built under R version 4.2.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'

The following object is masked from 'package:psych':

    logit

The following object is masked from 'package:purrr':

    some

The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"pacman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'pacman' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"Rcpp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cargar-base-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="cargar-base-de-datos">Cargar Base de datos</h3>
<p>Posteriormente, seleccionamos la base de datos que corresponde a los datos primarios obtenidos por “EL SOC” de la cual a partir de alli obtendremos nuestra información y variables, para posteriormente trabajar con estos datos, según corresponda el lineamiento investigativo del presente trabajo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>ELSOC_2016_2022 <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">"~/R-2024/Trabajo-2/Git hub/Input/ELSOC.2016.2022.sav"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="procesamiento-nueva-bb.dd" class="level3">
<h3 class="anchored" data-anchor-id="procesamiento-nueva-bb.dd">Procesamiento nueva BB.DD</h3>
<p>En este apartado, procesamos la base de datos específicamente, generando la obtención de una base de datos nueva, que corresponde a la utilización de las variables específicas que<br>
se trabajarán en el presente estudio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> ELSOC_2016_2022 <span class="sc">%&gt;%</span> <span class="fu">select</span>(c05_01,<span class="co">#Confianza gob</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>                                        c05_02,<span class="co">#Confianza Part Pol</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                                        c05_07,<span class="co">#Confianza Congreso N</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>                                        c13,<span class="co">#Interes politica</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>                                        c38,<span class="co">#Percepcion corrupcion pol</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>                                        sexo_enc,<span class="co">#sexo</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>                                        edad_enc)<span class="co">#edad</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="revisión-de-na-casos-perdidos" class="level3">
<h3 class="anchored" data-anchor-id="revisión-de-na-casos-perdidos">Revisión de NA (casos perdidos)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c05_01, <span class="at">exclude =</span> F) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-999 -888 -666    1    2    3    4    5 
  28   47    8 7650 5115 3736 1155  296 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c05_02, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 -999  -888  -666     1     2     3     4     5 
   45    92     8 12424  3710  1576   147    33 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c05_07, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-999 -888 -666    1    2    3    4    5 
  35  171    8 9707 4631 2917  479   87 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c13, <span class="at">exclude =</span> F) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-999 -888 -666    1    2    3    4    5 
  15   23    8 9188 3676 2912 1513  700 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c38, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-999 -888 -666    1    2    3    4    5 &lt;NA&gt; 
  58  244   10  172  470 1103 4378 6195 5405 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>sexo_enc, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2  &lt;NA&gt; 
 1735 10140  6160 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>edad_enc, <span class="at">exclude =</span> F) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34 
  19   40    9  121   13   62  110  156  138  129  258  167  226  159  175   65 
  35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50 
 305  285  185  247  227  253  404   83  204  266  142  461  483  272  193  262 
  51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   68 
 284   87  107   64  209  317  167  228  177  259  367  149  190   98  244   13 
  72   74   75   78 &lt;NA&gt; 
  23   36   51   16 8830 </code></pre>
</div>
</div>
</section>
<section id="filtrar-según-rango-etario" class="level3">
<h3 class="anchored" data-anchor-id="filtrar-según-rango-etario">Filtrar según Rango etario</h3>
<p>Aquí fundamentalmente filtramos una nueva base de datos en relación a un filtro que corresponde a un rango etario específico de población como propuesta de analisis en el presente trabajo, y que corresponde a la población más joven que respondió la encuesta ELSCOC, y que consta de una edad que varía de entre los 18 a 30 años.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil <span class="ot">&lt;-</span> <span class="fu">subset</span>(proc_data, edad_enc <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">&amp;</span> edad_enc <span class="sc">&lt;=</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="eliminar-casos-perdidos" class="level3">
<h3 class="anchored" data-anchor-id="eliminar-casos-perdidos">Eliminar casos perdidos</h3>
<section id="para-un-analisis-mejor-acotado-planetemoas-la-elinminación-de-los-casos-perdidos-de-las-variables-con-las-que-trabajaremos." class="level5">
<h5 class="anchored" data-anchor-id="para-un-analisis-mejor-acotado-planetemoas-la-elinminación-de-los-casos-perdidos-de-las-variables-con-las-que-trabajaremos.">Para un analisis mejor acotado, planetemoas la elinminación de los casos perdidos de las variables con las que trabajaremos.</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>c05_01 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>c05_01, <span class="st">"c(-999,-888,-777,-666)=NA"</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>c05_02 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>c05_02, <span class="st">"c(-999,-888,-777,-666)=NA"</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>c05_07 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>c05_07, <span class="st">"c(-999,-888,-777,-666)=NA"</span>)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>c13 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>c13, <span class="st">"c(-999,-888,-777,-666)=NA"</span>)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>c38 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>c38, <span class="st">"c(-999,-888,-777,-666)=NA"</span>)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>sexo_enc <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>sexo_enc, <span class="st">"c(-2,-1)=NA"</span>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>edad_enc <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>edad_enc, <span class="st">"c(-2,-1)=NA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="revision-de-eliminación-na" class="level3">
<h3 class="anchored" data-anchor-id="revision-de-eliminación-na">Revision de eliminación NA</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c05_01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Grado de confianza: El Gobierno (x) &lt;numeric&gt; 
# total N=1222 valid N=1217 mean=2.09 sd=1.02

Value |                                 Label |   N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------------
 -999 |                           No Responde |   0 |  0.00 |    0.00 |   0.00
 -888 |                               No Sabe |   0 |  0.00 |    0.00 |   0.00
 -777 |       Valor perdido por error tecnico |   0 |  0.00 |    0.00 |   0.00
 -666 | Valor perdido por encuesta incompleta |   0 |  0.00 |    0.00 |   0.00
    1 |                                  Nada | 428 | 35.02 |   35.17 |  35.17
    2 |                                  Poca | 380 | 31.10 |   31.22 |  66.39
    3 |                                  Algo | 304 | 24.88 |   24.98 |  91.37
    4 |                              Bastante |  79 |  6.46 |    6.49 |  97.86
    5 |                                 Mucha |  26 |  2.13 |    2.14 | 100.00
 &lt;NA&gt; |                                  &lt;NA&gt; |   5 |  0.41 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c05_02)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Grado de confianza: Los Partidos Politicos (x) &lt;numeric&gt; 
# total N=1222 valid N=1211 mean=1.46 sd=0.74

Value |                                 Label |   N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------------
 -999 |                           No Responde |   0 |  0.00 |    0.00 |   0.00
 -888 |                               No Sabe |   0 |  0.00 |    0.00 |   0.00
 -777 |       Valor perdido por error tecnico |   0 |  0.00 |    0.00 |   0.00
 -666 | Valor perdido por encuesta incompleta |   0 |  0.00 |    0.00 |   0.00
    1 |                                  Nada | 808 | 66.12 |   66.72 |  66.72
    2 |                                  Poca | 273 | 22.34 |   22.54 |  89.27
    3 |                                  Algo | 114 |  9.33 |    9.41 |  98.68
    4 |                              Bastante |  11 |  0.90 |    0.91 |  99.59
    5 |                                 Mucha |   5 |  0.41 |    0.41 | 100.00
 &lt;NA&gt; |                                  &lt;NA&gt; |  11 |  0.90 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c05_07)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Grado de confianza: El Congreso Nacional (x) &lt;numeric&gt; 
# total N=1222 valid N=1214 mean=1.87 sd=0.92

Value |                                 Label |   N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------------
 -999 |                           No Responde |   0 |  0.00 |    0.00 |   0.00
 -888 |                               No Sabe |   0 |  0.00 |    0.00 |   0.00
 -777 |       Valor perdido por error tecnico |   0 |  0.00 |    0.00 |   0.00
 -666 | Valor perdido por encuesta incompleta |   0 |  0.00 |    0.00 |   0.00
    1 |                                  Nada | 525 | 42.96 |   43.25 |  43.25
    2 |                                  Poca | 392 | 32.08 |   32.29 |  75.54
    3 |                                  Algo | 246 | 20.13 |   20.26 |  95.80
    4 |                              Bastante |  36 |  2.95 |    2.97 |  98.76
    5 |                                 Mucha |  15 |  1.23 |    1.24 | 100.00
 &lt;NA&gt; |                                  &lt;NA&gt; |   8 |  0.65 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c13)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Interes en la politica (x) &lt;numeric&gt; 
# total N=1222 valid N=1221 mean=2.01 sd=1.18

Value |                                 Label |   N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------------
 -999 |                           No Responde |   0 |  0.00 |    0.00 |   0.00
 -888 |                               No Sabe |   0 |  0.00 |    0.00 |   0.00
 -777 |       Valor perdido por error tecnico |   0 |  0.00 |    0.00 |   0.00
 -666 | Valor perdido por encuesta incompleta |   0 |  0.00 |    0.00 |   0.00
    1 |                       Nada interesado | 573 | 46.89 |   46.93 |  46.93
    2 |                       Poco interesado | 276 | 22.59 |   22.60 |  69.53
    3 |                       Algo interesado | 209 | 17.10 |   17.12 |  86.65
    4 |                   Bastante interesado | 111 |  9.08 |    9.09 |  95.74
    5 |                        Muy interesado |  52 |  4.26 |    4.26 | 100.00
 &lt;NA&gt; |                                  &lt;NA&gt; |   1 |  0.08 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c38)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Extension de corrupcion politica (x) &lt;numeric&gt; 
# total N=1222 valid N=1203 mean=4.23 sd=0.92

Value |                                 Label |   N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------------
 -999 |                           No Responde |   0 |  0.00 |    0.00 |   0.00
 -888 |                               No Sabe |   0 |  0.00 |    0.00 |   0.00
 -777 |       Valor perdido por error tecnico |   0 |  0.00 |    0.00 |   0.00
 -666 | Valor perdido por encuesta incompleta |   0 |  0.00 |    0.00 |   0.00
    1 |                        Nada extendida |  25 |  2.05 |    2.08 |   2.08
    2 |                        Poco extendida |  47 |  3.85 |    3.91 |   5.99
    3 |                        Algo extendida | 108 |  8.84 |    8.98 |  14.96
    4 |                    Bastante extendida | 464 | 37.97 |   38.57 |  53.53
    5 |                         Muy extendida | 559 | 45.74 |   46.47 | 100.00
 &lt;NA&gt; |                                  &lt;NA&gt; |  19 |  1.55 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>sexo_enc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sexo del encuestador/a (x) &lt;numeric&gt; 
# total N=1222 valid N=995 mean=1.70 sd=0.46

Value |  Label |   N | Raw % | Valid % | Cum. %
-----------------------------------------------
    1 | Hombre | 302 | 24.71 |   30.35 |  30.35
    2 |  Mujer | 693 | 56.71 |   69.65 | 100.00
 &lt;NA&gt; |   &lt;NA&gt; | 227 | 18.58 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>edad_enc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Edad del encuestador/a (x) &lt;numeric&gt; 
# total N=1222 valid N=1222 mean=26.54 sd=2.90

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
   19 |  19 |  1.55 |    1.55 |   1.55
   20 |  40 |  3.27 |    3.27 |   4.83
   21 |   9 |  0.74 |    0.74 |   5.56
   22 | 121 |  9.90 |    9.90 |  15.47
   23 |  13 |  1.06 |    1.06 |  16.53
   24 |  62 |  5.07 |    5.07 |  21.60
   25 | 110 |  9.00 |    9.00 |  30.61
   26 | 156 | 12.77 |   12.77 |  43.37
   27 | 138 | 11.29 |   11.29 |  54.66
   28 | 129 | 10.56 |   10.56 |  65.22
   29 | 258 | 21.11 |   21.11 |  86.33
   30 | 167 | 13.67 |   13.67 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
</section>
<section id="visualizar-nombres" class="level3">
<h3 class="anchored" data-anchor-id="visualizar-nombres">Visualizar nombres</h3>
<p>Para una mejor fundamentación, en el presente estudio se emplearán 7 variables del total de datos que brinda ELSOC. En donde las variables a trabajar constan de: Grado de confianza en el gobierno, Grado de confianza en Los Partidos Políticos, Grado de Confianza en El Congreso Nacional. Ambas tres variables forman parte de un analisis del grado de confianza con las 3 instituciones politicas mas importantes de la democracia Chilena representativa. Ademas, de igual manera se utilizara la variable que se relaciona conforme al interes que tienen las personas en la Politica en general, asi como tambien la percepción de estos mismos con la corrupción politica. En ese sentido tambien se empleara el tipo sexo de la persona y su respectiva edad del encuestado.</p>
<p>Variables que nos serviran para lograr entender si realmente existe una alto indice de desconfianza en la institucionalidad politica, pudiendo analizar cual es el relacionamiento con el andamiaje politico entre personas en un rango etario mas joven, y segmentadas por sexo hombre/mujer.</p>
<p>Primero, es importante visualizar los nombres de las variables para indagar en ellas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(proc_data_fil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "c05_01"   "c05_02"   "c05_07"   "c13"      "c38"      "sexo_enc" "edad_enc"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_label</span>(proc_data_fil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      c05_01 
           "Grado de confianza: El Gobierno" 
                                      c05_02 
"Grado de confianza: Los Partidos Politicos" 
                                      c05_07 
  "Grado de confianza: El Congreso Nacional" 
                                         c13 
                    "Interes en la politica" 
                                         c38 
          "Extension de corrupcion politica" 
                                    sexo_enc 
                    "Sexo del encuestador/a" 
                                    edad_enc 
                    "Edad del encuestador/a" </code></pre>
</div>
</div>
<p>Modificamos los nombres de las variables para un mejor entendimiento y una mayor claridad lectiva de estas mismas variables empleadas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil <span class="ot">&lt;-</span> proc_data_fil <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"conf_gob"</span><span class="ot">=</span>c05_01, <span class="co"># Confianza gobierno</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"conf_partpol"</span><span class="ot">=</span>c05_02, <span class="co"># Confianza partidos politicos</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"conf_cong"</span><span class="ot">=</span>c05_07, <span class="co"># Confianza Congreso Nacional</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"legt_pol"</span><span class="ot">=</span>c13, <span class="co"># Legitimación Politica</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"percp_corrup"</span><span class="ot">=</span>c38) <span class="co">#Percepción Corrupción Politica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_gob <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>conf_gob,<span class="at">label =</span> <span class="st">"Confianza: Gobierno"</span>)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>conf_gob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confianza: Gobierno"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_partpol <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>conf_partpol,<span class="at">label =</span> <span class="st">"Confianza: P.Politico"</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>conf_partpol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confianza: P.Politico"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_cong <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>conf_cong,<span class="at">label =</span> <span class="st">"Confianza: Congreso"</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>conf_cong)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confianza: Congreso"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>legt_pol <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>legt_pol,<span class="at">label =</span> <span class="st">"Legitimación: Politica"</span>)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>legt_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Legitimación: Politica"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>percp_corrup <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>percp_corrup,<span class="at">label =</span> <span class="st">"Percepcion: Corrupcion"</span>)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>percp_corrup)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Percepcion: Corrupcion"</code></pre>
</div>
</div>
</section>
<section id="obtener-datos-descriptivos" class="level3">
<h3 class="anchored" data-anchor-id="obtener-datos-descriptivos">Obtener datos descriptivos</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(proc_data_fil,</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>,<span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>))<span class="sc">%&gt;%</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(.,<span class="st">"markdown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 3%">
<col style="width: 15%">
<col style="width: 26%">
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">conf_gob</td>
<td style="text-align: left;">Confianza: Gobierno</td>
<td style="text-align: right;">1217</td>
<td style="text-align: right;">0.4091653</td>
<td style="text-align: right;">2.092030</td>
<td style="text-align: right;">1.0226436</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">conf_partpol</td>
<td style="text-align: left;">Confianza: P.Politico</td>
<td style="text-align: right;">1211</td>
<td style="text-align: right;">0.9001637</td>
<td style="text-align: right;">1.457473</td>
<td style="text-align: right;">0.7354989</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">conf_cong</td>
<td style="text-align: left;">Confianza: Congreso</td>
<td style="text-align: right;">1214</td>
<td style="text-align: right;">0.6546645</td>
<td style="text-align: right;">1.866557</td>
<td style="text-align: right;">0.9207609</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">legt_pol</td>
<td style="text-align: left;">Legitimación: Politica</td>
<td style="text-align: right;">1221</td>
<td style="text-align: right;">0.0818331</td>
<td style="text-align: right;">2.011466</td>
<td style="text-align: right;">1.1783009</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">percp_corrup</td>
<td style="text-align: left;">Percepcion: Corrupcion</td>
<td style="text-align: right;">1203</td>
<td style="text-align: right;">1.5548282</td>
<td style="text-align: right;">4.234414</td>
<td style="text-align: right;">0.9184263</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">sexo_enc</td>
<td style="text-align: left;">Sexo del encuestador/a</td>
<td style="text-align: right;">995</td>
<td style="text-align: right;">18.5761047</td>
<td style="text-align: right;">1.696482</td>
<td style="text-align: right;">0.4600080</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">edad_enc</td>
<td style="text-align: left;">Edad del encuestador/a</td>
<td style="text-align: right;">1222</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">26.542553</td>
<td style="text-align: right;">2.9037646</td>
<td style="text-align: left;">11 (19-30)</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(proc_data_fil)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(proc_data_fil, <span class="at">type=</span><span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
==========================================
Statistic      N    Mean  St. Dev. Min Max
------------------------------------------
conf_gob     1,217 2.092   1.023    1   5 
conf_partpol 1,211 1.457   0.735    1   5 
conf_cong    1,214 1.867   0.921    1   5 
legt_pol     1,221 2.011   1.178    1   5 
percp_corrup 1,203 4.234   0.918    1   5 
sexo_enc      995  1.696   0.460    1   2 
edad_enc     1,222 26.543  2.904   19  30 
------------------------------------------</code></pre>
</div>
</div>
<p>En estas tablas, a simple vista podemos visualizar los casos que se encuentran en cada respectiva variable, en donde se adjunta en cada variable su respectivo valor, su nombre, la media, la desviación estándar, y el rango de respuesta que tuvo cada variable por sí sola. En mayor detalle no indagaremos ya que posteriomente adentrarnos en un analisis mas profundo. Sin embargo, a muy grandes rasgos se puede decir que la cantidad de observación es por cada variable, aproximadamente oscila entre 1204 y 1221, en donde la confianza en en los partidos políticos representa la media más baja de las 3 instituciones a analizar adquiriendo un valor de 1.457, mientras que es seguida por la confianza en el Congreso Nacional que tuvo un valor de 1.866. Por su parte la mayor confianza de estas instituciones la tiene el Gobierno, adscribiendo como promedio la categoría de respuesta Poca desconfianza. Ademas, la cateogria de legitimacion politica en relación al interes por esta, adquiere valores entorno a una categoria de poco interes en la politica.</p>
<p>Fundamentalmente, otro valor importante a destacar hace referencia con la alta percepción de corrupción que existe entre los datos analizados, que apelan a la percepción de una alta corrupcion extendida en la politica, teniendo una media de 4.23 en una categoria de respuesta donde el valor mas alto es 5 (Muy extendida).</p>
<p>En resumen, la tabla proporciona información sobre la confianza en diferentes aspectos del gobierno y la política, así como sobre la legitimación política y la percepción de la corrupción. Las medias y desviaciones estándar muestran cómo varían estas medidas entre la población estudiada, mientras que los intervalos de confianza indican la incertidumbre asociada con estas estimaciones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>summarytools<span class="sc">::</span><span class="fu">dfSummary</span>(proc_data_fil, <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>### Data Frame Summary  
#### proc_data_fil  
**Dimensions:** 1222 x 7  
**Duplicates:** 302  

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
No   Variable                               Label                    Stats / Values            Freqs (% of Valid)   Graph                                    Valid      Missing  
---- -------------------------------------- ------------------------ ------------------------- -------------------- ---------------------------------------- ---------- ---------
1    conf_gob\                              Confianza: Gobierno      Mean (sd) : 2.1 (1)\      1 : 428 (35.2%)\     IIIIIII \                                1217\      5\       
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 380 (31.2%)\     IIIIII \                                 (99.6%)    (0.4%)   
                                                                     1 &lt; 2 &lt; 5\                3 : 304 (25.0%)\     IIII \                                                       
                                                                     IQR (CV) : 2 (0.5)        4 :  79 ( 6.5%)\     I \                                                          
                                                                                               5 :  26 ( 2.1%)                                                                   

2    conf_partpol\                          Confianza: P.Politico    Mean (sd) : 1.5 (0.7)\    1 : 808 (66.7%)\     IIIIIIIIIIIII \                          1211\      11\      
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 273 (22.5%)\     IIII \                                   (99.1%)    (0.9%)   
                                                                     1 &lt; 1 &lt; 5\                3 : 114 ( 9.4%)\     I \                                                          
                                                                     IQR (CV) : 1 (0.5)        4 :  11 ( 0.9%)\     \                                                            
                                                                                               5 :   5 ( 0.4%)                                                                   

3    conf_cong\                             Confianza: Congreso      Mean (sd) : 1.9 (0.9)\    1 : 525 (43.2%)\     IIIIIIII \                               1214\      8\       
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 392 (32.3%)\     IIIIII \                                 (99.3%)    (0.7%)   
                                                                     1 &lt; 2 &lt; 5\                3 : 246 (20.3%)\     IIII \                                                       
                                                                     IQR (CV) : 1 (0.5)        4 :  36 ( 3.0%)\     \                                                            
                                                                                               5 :  15 ( 1.2%)                                                                   

4    legt_pol\                              Legitimación: Politica   Mean (sd) : 2 (1.2)\      1 : 573 (46.9%)\     IIIIIIIII \                              1221\      1\       
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 276 (22.6%)\     IIII \                                   (99.9%)    (0.1%)   
                                                                     1 &lt; 2 &lt; 5\                3 : 209 (17.1%)\     III \                                                        
                                                                     IQR (CV) : 2 (0.6)        4 : 111 ( 9.1%)\     I \                                                          
                                                                                               5 :  52 ( 4.3%)                                                                   

5    percp_corrup\                          Percepcion: Corrupcion   Mean (sd) : 4.2 (0.9)\    1 :  25 ( 2.1%)\     \                                        1203\      19\      
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 :  47 ( 3.9%)\     \                                        (98.4%)    (1.6%)   
                                                                     1 &lt; 4 &lt; 5\                3 : 108 ( 9.0%)\     I \                                                          
                                                                     IQR (CV) : 1 (0.2)        4 : 464 (38.6%)\     IIIIIII \                                                    
                                                                                               5 : 559 (46.5%)      IIIIIIIII                                                    

6    sexo_enc\                              Sexo del encuestador/a   Min  : 1\                 1 : 302 (30.4%)\     IIIIII \                                 995\       227\     
     [haven_labelled, vctrs_vctr, double]                            Mean : 1.7\               2 : 693 (69.6%)      IIIIIIIIIIIII                            (81.4%)    (18.6%)  
                                                                     Max  : 2                                                                                                    

7    edad_enc\                              Edad del encuestador/a   Mean (sd) : 26.5 (2.9)\   12 distinct values   \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\   1222\      0\       
     [numeric]                                                       min &lt; med &lt; max:\                              \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\   (100.0%)   (0.0%)   
                                                                     19 &lt; 27 &lt; 30\                                  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\                       
                                                                     IQR (CV) : 4 (0.1)                             \ \ \ \ . \ \ \ \ . : . . :\                                 
                                                                                                                    . \ \ : \ \ . : : : : :                                      
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>En esta tabla, a modo particular podemos indagar en una aproximación de lo que vendría siendo la distribución de cada variable. Aquí, ya podemos realizar un análisis en profundidad, en donde en primera instancia se observa que el grado de confianza en la institución de gobierno es bajísima, pero siendo la que relativamente genera más confianza en la población de estudio. Por su parte, la institucionalidad de los partidos políticos es sobre quien más recae el cuestionamiento sobre la desconfianza, obteniendo esta variable la peor evaluación. El congreso nacional, también tiene un bajo nivel de desconfianza, siendo un poco más baja la desconfianza que la institución de gobierno como tal. En cuanto al interés en la política, se deja a entrever a grandes rasgos que la población joven, prácticamente en más de un 50% no tiene mayor interés en esta perspectiva. Por último, en cuanto a la percepción de corrupción política que presenta el rango etario de 18 a 30 años, nos expresa que la mayor parte de esta población siente que la corrupción política se encuentra entre algo extendida y muy extendida en nuestro país.</p>
</section>
<section id="tablas-de-contigencia" class="level3">
<h3 class="anchored" data-anchor-id="tablas-de-contigencia">Tablas de contigencia</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(proc_data_fil<span class="sc">$</span>legt_pol, proc_data_fil<span class="sc">$</span>sexo_enc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Legitimación:<br>Politica</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">Sexo del<br>encuestador/a</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Hombre</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Mujer</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Nada interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">134</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">321</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">455</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Poco interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">73</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">163</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">236</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Algo interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">54</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">117</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">171</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Bastante interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">28</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">62</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">90</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Muy interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">12</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">30</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">42</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">301</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">693</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">994</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">χ<sup>2</sup>=0.420 · df=4 · Cramer's V=0.021 · p=0.981</td> 
</tr>
 
</tbody></table>
</div>
</div>
<p>En esta tabla podemos ejemplificar la legitimacion politica en relación a una clara distinción entre sexos, en donde se deja a entrever que son en mayor medida la categoría de nada interesado en la política se retrae a la mayor cantidad de respuestas estipuladas, en donde también se deja a entrever una mayor cantidad de mujeres quienes respondieron la encuesta del total de la población encuestada. En ese sentido la mayor cantidad de respuestas en ambos sexos se concentra en la categoría ya mencionada, afirmando que aprox. mas del 50% de los encuestados afirma no estar nada interesado en política.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(proc_data_fil<span class="sc">$</span>percp_corrup, proc_data_fil<span class="sc">$</span>sexo_enc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Percepcion:<br>Corrupcion</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">Sexo del<br>encuestador/a</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Hombre</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Mujer</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Nada extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">6</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">14</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">20</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Poco extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">13</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">28</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">41</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Algo extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">23</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">67</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">90</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Bastante extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">116</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">272</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">388</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Muy extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">138</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">306</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">444</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">296</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">687</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">983</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">χ<sup>2</sup>=1.144 · df=4 · Cramer's V=0.034 · p=0.887</td> 
</tr>
 
</tbody></table>
</div>
</div>
<p>De igual manera, en relacion a la tabla de contingencia sobre la precepcion de corrupción se observa que gran cantidad de la poblacion total encuestada (ya sea hombre o mujer) afirma que la corrupción politica se encuentra bastante o muy extendida en nuestro pais, siendo un claro indice de una falta de seriedad y profesinalismo en materia politica debido al actuar de estos sujetos gubernamentales.</p>
</section>
<section id="tablas-con-porcentajes" class="level3">
<h3 class="anchored" data-anchor-id="tablas-con-porcentajes">Tablas con porcentajes</h3>
<p>Para mas detalles adjuntamos la realizacion de las mismas tables anteriormente estipulados, pero con la expecion de un analisis en porcentajes para un estudio mas detallado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(proc_data_fil<span class="sc">$</span>percp_corrup, proc_data_fil<span class="sc">$</span>edad_enc,</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.col.prc=</span><span class="cn">TRUE</span>,</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.summary=</span><span class="cn">FALSE</span>,</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">encoding =</span> <span class="st">"UTF-8"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Percepcion:<br>Corrupcion</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="12">Edad del<br>encuestador/a</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">19</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">20</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">21</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">22</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">23</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">24</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">25</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">26</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">27</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">28</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">29</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">30</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Nada extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#339933;">5.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#339933;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#339933;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">6</span><br><span style="color:#339933;">5.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#339933;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#339933;">1.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#339933;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">3</span><br><span style="color:#339933;">2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#339933;">1.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#339933;">0.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">9</span><br><span style="color:#339933;">3.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#339933;">1.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">25</span><br><span style="color:#339933;">2.1&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Poco extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#339933;">5.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#339933;">2.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#339933;">11.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">4</span><br><span style="color:#339933;">3.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#339933;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#339933;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">6</span><br><span style="color:#339933;">5.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">11</span><br><span style="color:#339933;">7.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">3</span><br><span style="color:#339933;">2.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">4</span><br><span style="color:#339933;">3.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">9</span><br><span style="color:#339933;">3.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">7</span><br><span style="color:#339933;">4.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">47</span><br><span style="color:#339933;">3.9&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Algo extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">4</span><br><span style="color:#339933;">21.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#339933;">5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#339933;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">10</span><br><span style="color:#339933;">8.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#339933;">15.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#339933;">3.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">21</span><br><span style="color:#339933;">19.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">10</span><br><span style="color:#339933;">6.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">14</span><br><span style="color:#339933;">10.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">12</span><br><span style="color:#339933;">9.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">26</span><br><span style="color:#339933;">10.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">5</span><br><span style="color:#339933;">3.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">108</span><br><span style="color:#339933;">9&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Bastante extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">8</span><br><span style="color:#339933;">42.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">14</span><br><span style="color:#339933;">35&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">6</span><br><span style="color:#339933;">66.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">41</span><br><span style="color:#339933;">34.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">5</span><br><span style="color:#339933;">38.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">18</span><br><span style="color:#339933;">29&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">51</span><br><span style="color:#339933;">46.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">55</span><br><span style="color:#339933;">36.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">60</span><br><span style="color:#339933;">44.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">42</span><br><span style="color:#339933;">32.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">108</span><br><span style="color:#339933;">41.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">56</span><br><span style="color:#339933;">34.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">464</span><br><span style="color:#339933;">38.6&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Muy extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">5</span><br><span style="color:#339933;">26.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">23</span><br><span style="color:#339933;">57.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#339933;">22.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">57</span><br><span style="color:#339933;">48.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">6</span><br><span style="color:#339933;">46.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">41</span><br><span style="color:#339933;">66.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">31</span><br><span style="color:#339933;">28.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">71</span><br><span style="color:#339933;">47.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">57</span><br><span style="color:#339933;">41.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">69</span><br><span style="color:#339933;">53.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">106</span><br><span style="color:#339933;">41.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">91</span><br><span style="color:#339933;">56.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">559</span><br><span style="color:#339933;">46.5&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">19</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">40</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">9</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">118</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">13</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">62</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">109</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">150</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">136</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">128</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">258</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">161</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1203</span><br><span style="color:#339933;">100&nbsp;%</span></td> 
</tr>
 
</tbody></table>
</div>
</div>
<p>Aqui, en esta tabla con porcentajes observamos que entre las personas de 18 a 30 años, tan solo el 2,1%, es decir, 25 personas, comsiderar que la percepción de corrupcion politica se encuentra para Nada extendida en nuestro pais, de un total de 1203 encuestados. Por el contrario, de esos 1203 personas jovenes de entre 18 a 30 años, un ttoal de 559, es decir, cerca de la mitad de los encuestados (46,5%) afirma expresamente que la corrupción politica se encuentra muy extendida.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(proc_data_fil<span class="sc">$</span>legt_pol, proc_data_fil<span class="sc">$</span>sexo_enc,</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.col.prc=</span><span class="cn">TRUE</span>,</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.summary=</span><span class="cn">FALSE</span>,</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">encoding =</span> <span class="st">"UTF-8"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Legitimación:<br>Politica</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">Sexo del<br>encuestador/a</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Hombre</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Mujer</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Nada interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">134</span><br><span style="color:#339933;">44.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">321</span><br><span style="color:#339933;">46.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">455</span><br><span style="color:#339933;">45.8&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Poco interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">73</span><br><span style="color:#339933;">24.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">163</span><br><span style="color:#339933;">23.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">236</span><br><span style="color:#339933;">23.7&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Algo interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">54</span><br><span style="color:#339933;">17.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">117</span><br><span style="color:#339933;">16.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">171</span><br><span style="color:#339933;">17.2&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Bastante interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">28</span><br><span style="color:#339933;">9.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">62</span><br><span style="color:#339933;">8.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">90</span><br><span style="color:#339933;">9.1&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Muy interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">12</span><br><span style="color:#339933;">4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">30</span><br><span style="color:#339933;">4.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">42</span><br><span style="color:#339933;">4.2&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">301</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">693</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">994</span><br><span style="color:#339933;">100&nbsp;%</span></td> 
</tr>
 
</tbody></table>
</div>
</div>
<p>En relacion a esta tabla se identifica que en promedio es casi el mismo porcentaje de hombres y mujeres que no se encuentran para nada interesadoas en la politica institucional de nuestro pais. Ademas, tambien se del total de encuestados, entre hombres y mujeres,, un 4,2% expresa que se encuentra muy interesado en la politica. Se expresa que no hay diferencias claramente significativas entre ambos generos en relacion a la variable de legitimación politica. De igual manera es importante recalcar que las diferencias en relacio a la cantidad de encuestados, dice relacion con una mayor poblacion femenina en la muestra analisasa en la base de datos de este estudio.</p>
</section>
<section id="graficos" class="level3">
<h3 class="anchored" data-anchor-id="graficos">Graficos</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> legt_pol)) <span class="sc">+</span> </span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"coral"</span>)<span class="sc">+</span></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Grado de percepción de legitimación politica"</span>,</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Percepción de Legitimación Politica"</span>,</span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="2.practico_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Con base en los datos proporcionados, es evidente que existe una baja percepción de legitimación política en Chile. Esto se refleja en los niveles de interés político de la población, donde la mayoría de los encuestados se encuentran en las categorías de “Nada interesado” y “Poco interesado”, representando el 45% y el 24% respectivamente. El nivel de interés político aumenta gradualmente a medida que avanzamos hacia las categorías de “Algo interesado”, “Bastante interesado” y “Muy interesado”, con porcentajes significativamente menores en comparación con los niveles de desinterés. Esto sugiere que una parte sustancial de la población chilena no se siente involucrada o comprometida con la política, lo que puede tener implicaciones negativas para la legitimidad y la estabilidad del sistema político.</p>
<p>Esta baja percepción de legitimación política puede estar relacionada con una serie de factores, como la falta de representatividad de las instituciones políticas, la corrupción, la desigualdad socioeconómica o la percepción de que las acciones del gobierno no satisfacen las necesidades y demandas de la población.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> percp_corrup)) <span class="sc">+</span> </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"coral"</span>)<span class="sc">+</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Grado de percepción de corrupción  politica"</span>,</span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Percepción de corrupción Politica"</span>,</span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 19 rows containing non-finite outside the scale range
(`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="2.practico_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En relacion a los datos obtenidos se observa una alta percepción de corrupción política en Chile en la pobalcion joven que ronda los 18 a 30 años. La mayoría de los encuestados perciben la corrupción como un problema significativo y que pareciera esta al latir de la sociedad chilena, en donde en un aproximado, mas de un 70% de esta poblacion de estudio indica que la corrupción en nuestro pais se encuentra entre “Bastante extendida” y “Muy extendida”. Afirmando de esta manera lo que en un principio se tenia como hipotesis de trabajo, que era que la poblacion joven, vale decir, la poblacion objetivo de este estudio, expresan altos estandares de malversación en el actuar politico, ya sea por diversos motivos.</p>
<p>En generla, se puede afirmar que la indagacion en estos datos sugieren que la corrupción política es un tema de gran preocupación para la población chilena joven, lo que puede tener consecuencias negativas para la confianza en las instituciones gubernamentales y para la legitimidad del sistema político de la democracia chilena en su conjunto.</p>
</section>
<section id="conclusiones-finales" class="level3">
<h3 class="anchored" data-anchor-id="conclusiones-finales">Conclusiones finales</h3>
<p>A grandes rasgos, se puede decir que la desconfianza en la institucionalidad política chilena, que incluye el Congreso, el gobierno y los partidos políticos, es un fenómeno complejo que refleja una serie de problemas arraigados en la sociedad. La literatura reciente, asi como el trabajo realizado en el presente estudio, en parte afirma que se puede concluir que esta desconfianza surge de una combinación de factores, que van desde la percepción de corrupción y falta de transparencia hasta la desconexión entre los líderes políticos y las necesidades reales de la ciudadanía.</p>
<p>En donde las instituciones políticas en Chile enfrentan desafíos significativos en términos de legitimidad y representatividad. La falta de responsabilidad, la opacidad en la toma de decisiones y los escándalos de corrupción han erosionado la confianza de la población en sus líderes y en las instituciones que los respaldan. Por ultimo, se hace relevante recalcar que la brecha entre las élites políticas y la ciudadanía común se ha ampliado, lo que ha generado un sentimiento de alienación y desapego hacia el sistema político generando una falta de interes. Y en donde en particular, los partidos politicos son percibidos como entidades distantes y desconectadas de las preocupaciones cotidianas de la gente, lo que ha contribuido a una creciente apatía y desinterés por la participación política.</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-laso2010" class="csl-entry" role="doc-biblioentry">
Laso, Esteban. 2010. <span>“Trust as a Crossroad: Culture, Development and Corruption.”</span> <em>Athenea Digital. Revista de Pensamiento e Investigación Social</em>, no. 17 (March): 97. <a href="https://doi.org/10.5565/rev/athenead/v0n17.654">https://doi.org/10.5565/rev/athenead/v0n17.654</a>.
</div>
<div id="ref-marchantsalamanca2021" class="csl-entry" role="doc-biblioentry">
Marchant Salamanca, Luz. 2021. <span>“La Crisis Política En Chile y El Rol de La Democracia Directa En La Recomposición de La Confianza Democrática y La Institucionalidad. Un Ensayo Para Ampliar La Mirada Sobre Las Experiencias Democráticas de Chile y Uruguay y Aportar En El Direccionamiento.”</span> <em>Encrucijada Americana</em> 13 (2): 85. <a href="https://doi.org/10.53689/ea.v13i2.181">https://doi.org/10.53689/ea.v13i2.181</a>.
</div>
<div id="ref-moralesquiroga2008" class="csl-entry" role="doc-biblioentry">
Morales Quiroga, Mauricio. 2008. <span>“Evaluando La Confianza Institucional En Chile: Una Mirada Desde Los Resultados LAPOP.”</span> <em>Revista de Ciencia Política (Santiago)</em> 28 (2). <a href="https://doi.org/10.4067/S0718-090X2008000200007">https://doi.org/10.4067/S0718-090X2008000200007</a>.
</div>
<div id="ref-moralesquiroga2020" class="csl-entry" role="doc-biblioentry">
———. 2020. <span>“Estallido Social En Chile 2019: Participación, Representación, Confianza Institucional y Escándalos Públicos.”</span> <em>Análisis Político</em> 33 (98): 3–25. <a href="https://doi.org/10.15446/anpol.v33n98.89407">https://doi.org/10.15446/anpol.v33n98.89407</a>.
</div>
<div id="ref-riffo2019" class="csl-entry" role="doc-biblioentry">
Riffo, Fabián, Daniela Pérez, César Antonio Salazar Espinoza, and Andrés Acuña Duarte. 2019. <span>“¿Qué Influye En La Confianza En Las Instituciones? Evidencia Empírica Para Chile.”</span> <em>Revista Facultad de Ciencias Económicas</em> 27 (2): 83–104. <a href="https://doi.org/10.18359/rfce.3517">https://doi.org/10.18359/rfce.3517</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>