<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Damián Céspedes">

<title>TrabajoR.3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="TRABAJO4RRRRRRR_files/libs/clipboard/clipboard.min.js"></script>
<script src="TRABAJO4RRRRRRR_files/libs/quarto-html/quarto.js"></script>
<script src="TRABAJO4RRRRRRR_files/libs/quarto-html/popper.min.js"></script>
<script src="TRABAJO4RRRRRRR_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="TRABAJO4RRRRRRR_files/libs/quarto-html/anchor.min.js"></script>
<link href="TRABAJO4RRRRRRR_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="TRABAJO4RRRRRRR_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="TRABAJO4RRRRRRR_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="TRABAJO4RRRRRRR_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="TRABAJO4RRRRRRR_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">TrabajoR.3</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Damián Céspedes </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="confianza-en-la-institucionalidad-politica-en-la-población-joven-de-entre-18-a-30-años" class="level2">
<h2 class="anchored" data-anchor-id="confianza-en-la-institucionalidad-politica-en-la-población-joven-de-entre-18-a-30-años">“Confianza en la institucionalidad politica en la población joven de entre 18 a 30 años”</h2>
<section id="introducción" class="level4">
<h4 class="anchored" data-anchor-id="introducción">Introducción</h4>
<p>Durante las últimas décadas, en latinoamérica se ha tendido a centrar el foco investigativo en torno a diferentes tipos de fenómenos sociales subyacentes. Esto se debe a que durante este último tiempo, el continente se ha caracterizado por la irrupción de diversas efervescencias en ámbitos sociales, políticos y económicos de gran magnitud. En esa línea, contextualmente, Chile representa un caso particular en donde, a partir del 18 de Octubre de 2019 se constituyó un punto de inflexión en la historia política y social del país. En aquella ocasión, los ciudadanos salieron a las calles de manera disgustada para exigir un sinnúmero de reformas sociales en materias como la salud, pensiones, educación, entre otras. Este suceso tomó forma clara a tal punto que llegó a convertirse en una suerte de llamada de atención para muchos sujetos del tapete político, quienes fueron interpelados críticamente debido a la mala interpretación por parte de ellos hacia las exigencias que demandaba la ciudadanía. Un descontento social que con el pasar del tiempo venía gestándose hacía varios años antes y que se exteriorizo mediante multitudinarias manifestaciones nunca antes vistas en aquel entonces.</p>
<p>En ese sentido, una de las grandes dificultades que enfrentamos como comunidad latina hace referencia a un progresivo incremento de desconfianza a la hora de hablar de la relación que logran establecer los actores políticos, quienes están al mando de la sociedad, con los mismos ciudadanos <span class="citation" data-cites="marchantsalamanca2021">[@marchantsalamanca2021]</span>. En el caso Chileno, esto queda especialmente contrastado con hallazgos anteriores expuestos por <span class="citation" data-cites="moralesquiroga2008">@moralesquiroga2008</span>, quien indaga en la relación entre la democracia y la confianza institucional, obteniendo como resultado una representación de insatisfacción y descontento por parte de la ciudadanía con algunos organismo del andamiaje politico-democrático. Con el paso del tiempo, se evidencia una clara reducción en la confianza en la gubernamentasbilidad institucional, que en ese entonces afectaba principalmente a organismos como el Gobierno, el Congreso y los partidos políticos <span class="citation" data-cites="moralesquiroga2020">[@moralesquiroga2020]</span>. Es decir,&nbsp;gran parte de la institucionalidad política representativa de la sociedad.</p>
<p>Para autores como <span class="citation" data-cites="laso2010">@laso2010</span>, la confianza institucional se asocia con la concepción de riesgo, entendiendo como puede uno generar (influir) y provocar cambios en los “niveles” subjetivos de confianza, ya sea disminuyéndolos o aumentándolos. El autor formula interesantes ideas al respecto, sugiriendo que el concepto en cuestión tendría dos niveles: las palabras y los actos. Según esta perspectiva, entonces la confianza se desarrolla cuando haya coincidencia entre ambas posturas, pero se perdería en cuanto exista discordancia entre ambas en cuanto tal (2010). Bajo esta línea argumentativa, consideraremos que la confianza institucional es una dimensión que abarca la coincidencia en la coherencia que tengan los actos y palabras por parte de las instituciones políticas, así como de los actores involucrados que forman parte de aquel organismo fundamental en una sociedad democratica. Por tanto, lo anterior nos permite suponer que cuando haya una discrepancia de estos sujetos entre lo dicho y lo hecho, ya sea por una mentira o un comportamiento inconsecuente, esto generará falta de credibilidad y, por consiguiente, la pérdida de confianza en las instituciones políticas mencionadas anteriormente.</p>
<p>Este mismo autor, <span class="citation" data-cites="laso2010">[@laso2010]</span>, además propone que la confianza en una sociedad con óptima funcionalidad de las instituciones ayudaría a reducir la complejidad y el desorden existentes en algunos ámbitos. Esto nos permite adentrarnos en la idea de que una sociedad en la cual prime la idea de desconfianza esta será una sociedad marcada por el desorden y eventuales crisis económicas, políticas y sociales. Es de importancia mencionar que a título de Laso, la confianza, restringida al ámbito humano (es decir a las relaciones entre personas, individuos o instituciones), no siempre será recíproca, ya que estas están determinadas por las conductas anteriores de estos mismos. Esto quiere decir que en una sociedad donde cierta parte de los individuos que tienen cargos políticos desempeñan funciones en base a malas prácticas en cierta medida cuestionables pues quebrantan a la comunidad, precisamente allí, es sumamente importante que las políticas públicas que se promuevan giren su foco en torno a la transparencia. Pues la importancia de la confianza institucional es fundamental para el funcionamiento de un régimen político y la estabilidad de una nación democratica.</p>
<p>Por su parte, autores como <span class="citation" data-cites="riffo2019">[@riffo2019]</span> expresan que existe una factor importante en relación con una gran preponderancia de la variable que ya hemos mencionado con anterioridad, es decir, la confianza institucional, en concordancia con lo que vendría siendo el capital social. El autor principalmente refiere a que esta interrelación de conceptos son aspectos que deben de ser fundamentales para las organizaciones democráticas, pudiendo así lograr tener la factibilidad de mejorar el fortalecimiento en la eficacia de la representación política de las sociedades. Desde esta perspectiva, aquello quiere decir que se concibe de cierta manera a la confianza institucional como una especie de versificación de la cohesión social dentro de la colectividad a la que se pertenece.</p>
<p>En esa línea, el contexto político Chileno ya mencionado deja a entrever un relativo aumento hacia la presentación de una situación sociopolítica compleja en cuanto a una relación de amplia distancia de desconfianza por parte de los ciudadanos, hacia gran parte de los sectores políticos y hacia sus diferentes posturas en las perspectivas polticas, ya sea de diversa ubicación en el entorno del contexto ideológico izquierda/derecha, sea el Gobierno de turno, Partidos Políticos y Congreso Nacional. En cierta medida, esto nos lleva a plantear la hipótesis central que encamina este trabajo, la cual refiere a que actualmente estamos frente a la presencia de una crisis de corte institucional en la gubernamentalidad política del país, manifestada en una en cuanto a una aparente baja progresiva en los estándares de confianza por parte de la ciudadanía frente a estos organismos políticos.</p>
<p>En concordancia con eso, la pregunta que guía este estudio es si las capacidades institucionales de los agentes políticos inciden en la confianza política que las personas depositan en ellos y, de existir tal influencia, cómo es dicha relación en cuanto a la fundamentacion con los estandares de confianza que se observan. Por tanto el argumento principal como ya ha sido sostenido con anterioridad refiere a que los actuales organismo políticos más importantes para la sociedad chilena (Gobierno, Partidos Políticos y Congresos) se encuentran en una crisis de desconfianza institucional por parte de la ciudadanía. Desde alli, intentaremos realizar un a segmentación por sexo, y además también interemos realiza un filtro por rangos etarios de la población más joven de adultos, que para efectos de este trabajo ronda entre los 18 a 30 años, quienes, segun la literatura son una de las poblaciones que mas lejania siente en relacion a al pertenencia con estas mismas organizaciones institucionales de la politica chilena.</p>
<p>A partir de alli, para efectos de la presente investigacion, recurrimos a una base de datos obtenida a traves de un estudio longitudinal realizado por el COES en Chile entre los años 2016 y 2022. Fundamentalmente, emplearemos los datos de ELSOC_2016_2022 con el fin de observar como se plasma la relación de confianza institucional de la ciudadania para con los entes politicos que estan al mando de la sociedad, para desde alli lograr plantear un analisis en mayor profundidad.</p>
</section>
<section id="trabajo-en-r" class="level3">
<h3 class="anchored" data-anchor-id="trabajo-en-r">Trabajo en R</h3>
<section id="ajustes-iniciales" class="level5">
<h5 class="anchored" data-anchor-id="ajustes-iniciales">Ajustes iniciales</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>()) <span class="co"># borrar todos los objetos en el espacio de trabajo</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>) <span class="co"># valores sin notación científica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="cargar-paquetes" class="level3">
<h3 class="anchored" data-anchor-id="cargar-paquetes">Cargar paquetes</h3>
<p>Para la realización del presente estudio, emplearemos la utilización de Rstudio para poder visualizar y trabajar con los datos, en donde trabajaremos mediante un R script. Como primer paso debemos cargar una serie de paquetes que nos permitan analizar y utilizar lo que necesitamos para fines investigativos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sjlabelled,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>               dplyr, <span class="co">#Manipulacion de datos</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>               stargazer, <span class="co">#Tablas</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>               sjmisc,<span class="co"># Tablas</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>               kableExtra, <span class="co">#Tablas</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>               sjPlot, <span class="co">#Tablas y gr�ficos</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>               corrplot, <span class="co"># Correlaciones</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>               sessioninfo, <span class="co"># Informaci�n de la sesi�n de trabajo</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>               ggplot2) <span class="co"># Para la mayor�a de los gr�ficos</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.1
✔ readr     2.1.5     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ tibble::add_case()       masks sjmisc::add_case()
✖ forcats::as_factor()     masks sjlabelled::as_factor()
✖ ggplot2::as_label()      masks dplyr::as_label(), sjlabelled::as_label()
✖ dplyr::filter()          masks stats::filter()
✖ kableExtra::group_rows() masks dplyr::group_rows()
✖ purrr::is_empty()        masks sjmisc::is_empty()
✖ dplyr::lag()             masks stats::lag()
✖ tidyr::replace_na()      masks sjmisc::replace_na()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"table1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'table1' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'table1'

The following objects are masked from 'package:base':

    units, units&lt;-</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"psych"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'psych' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'

The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"haven"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'haven' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'haven'

The following objects are masked from 'package:sjlabelled':

    as_factor, read_sas, read_spss, read_stata, write_sas, zap_labels</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"magrittr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'magrittr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'magrittr'

The following object is masked from 'package:purrr':

    set_names

The following object is masked from 'package:tidyr':

    extract</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"sjmisc"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"lm.beta"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lm.beta' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"Hmisc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'Hmisc' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Hmisc'

The following object is masked from 'package:psych':

    describe

The following objects are masked from 'package:table1':

    label, label&lt;-, units

The following object is masked from 'package:sjmisc':

    %nin%

The following objects are masked from 'package:dplyr':

    src, summarize

The following objects are masked from 'package:base':

    format.pval, units</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"PerformanceAnalytics"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'PerformanceAnalytics' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: xts
Loading required package: zoo

Attaching package: 'zoo'

The following objects are masked from 'package:base':

    as.Date, as.Date.numeric


Attaching package: 'xts'

The following objects are masked from 'package:dplyr':

    first, last


Attaching package: 'PerformanceAnalytics'

The following object is masked from 'package:graphics':

    legend</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"sjPlot"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"texreg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'texreg' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Version:  1.39.3
Date:     2023-11-09
Author:   Philip Leifeld (University of Essex)

Consider submitting praise using the praise or praise_interactive functions.
Please cite the JSS article in your publications -- see citation("texreg").

Attaching package: 'texreg'

The following object is masked from 'package:magrittr':

    extract

The following object is masked from 'package:tidyr':

    extract</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"car"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'carData' was built under R version 4.2.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'

The following object is masked from 'package:psych':

    logit

The following object is masked from 'package:purrr':

    some

The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"pacman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'pacman' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"Rcpp"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"haven"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggpubr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggpubr' was built under R version 4.2.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cargar-base-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="cargar-base-de-datos">Cargar Base de datos</h3>
<p>Posteriormente, seleccionamos la base de datos que corresponde a los datos primarios obtenidos por “EL SOC” de la cual a partir de alli obtendremos nuestra información y variables, para posteriormente trabajar con estos datos, según corresponda el lineamiento investigativo del presente trabajo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>ELSOC_2016_2022 <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">"~/R-2024/Trabajo-2/Git hub/Input/ELSOC.2016.2022.sav"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="procesamiento-nueva-bb.dd" class="level3">
<h3 class="anchored" data-anchor-id="procesamiento-nueva-bb.dd">Procesamiento nueva BB.DD</h3>
<p>En este apartado, procesamos la base de datos específicamente, generando la obtención de una base de datos nueva, que corresponde a la utilización de las variables específicas que se trabajarán en el presente estudio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> ELSOC_2016_2022 <span class="sc">%&gt;%</span> <span class="fu">select</span>(c05_01,<span class="co">#Confianza gob</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                                        c05_02,<span class="co">#Confianza Part Pol</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                                        c05_07,<span class="co">#Confianza Congreso </span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                                        c05_08, <span class="co">#Confianza Presidente de la Republica</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>                                        c13,<span class="co">#Interes politica</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>                                        c38,<span class="co">#Percepcion corrupcion pol</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>                                        c01,<span class="co"># Actitud hacia democracia</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>                                        sexo_enc,<span class="co">#sexo</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>                                        m01,</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>                                        edad_enc,)<span class="co">#edad</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="revisión-de-na-casos-perdidos" class="level3">
<h3 class="anchored" data-anchor-id="revisión-de-na-casos-perdidos">Revisión de NA (casos perdidos)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c05_01, <span class="at">exclude =</span> F) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-999 -888 -666    1    2    3    4    5 
  28   47    8 7650 5115 3736 1155  296 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c05_02, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 -999  -888  -666     1     2     3     4     5 
   45    92     8 12424  3710  1576   147    33 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c05_07, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-999 -888 -666    1    2    3    4    5 
  35  171    8 9707 4631 2917  479   87 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c05_08, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-999 -888    1    2    3    4    5 &lt;NA&gt; 
  40   52 7663 3632 3575 1506  566 1001 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c13, <span class="at">exclude =</span> F) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-999 -888 -666    1    2    3    4    5 
  15   23    8 9188 3676 2912 1513  700 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c38, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-999 -888 -666    1    2    3    4    5 &lt;NA&gt; 
  58  244   10  172  470 1103 4378 6195 5405 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>c01, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-999 -888 -666    1    2    3    4    5 
 123  519    8 6552 5133 4001 1345  354 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>sexo_enc, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2  &lt;NA&gt; 
 1735 10140  6160 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_data<span class="sc">$</span>edad_enc, <span class="at">exclude =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34 
  19   40    9  121   13   62  110  156  138  129  258  167  226  159  175   65 
  35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50 
 305  285  185  247  227  253  404   83  204  266  142  461  483  272  193  262 
  51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   68 
 284   87  107   64  209  317  167  228  177  259  367  149  190   98  244   13 
  72   74   75   78 &lt;NA&gt; 
  23   36   51   16 8830 </code></pre>
</div>
</div>
</section>
<section id="filtrar-según-rango-etario" class="level3">
<h3 class="anchored" data-anchor-id="filtrar-según-rango-etario">Filtrar según Rango etario</h3>
<p>Aquí fundamentalmente filtramos una nueva base de datos en relación a un filtro que corresponde a un rango etario específico de población como propuesta de analisis en el presente trabajo, y que corresponde a la población más joven que respondió la encuesta ELSCOC, y que consta de una edad que varía de entre los 18 a 30 años.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>proc_data_1 <span class="ot">&lt;-</span> <span class="fu">subset</span>(proc_data, edad_enc <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">&amp;</span> edad_enc <span class="sc">&lt;=</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="eliminar-casos-perdidos" class="level3">
<h3 class="anchored" data-anchor-id="eliminar-casos-perdidos">Eliminar casos perdidos</h3>
<section id="para-un-analisis-mejor-acotado-planetemoas-la-elinminación-de-los-casos-perdidos-de-las-variables-con-las-que-trabajaremos." class="level5">
<h5 class="anchored" data-anchor-id="para-un-analisis-mejor-acotado-planetemoas-la-elinminación-de-los-casos-perdidos-de-las-variables-con-las-que-trabajaremos.">Para un analisis mejor acotado, planetemoas la elinminación de los casos perdidos de las variables con las que trabajaremos.</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil <span class="ot">&lt;-</span> proc_data_1 <span class="sc">%&gt;%</span> <span class="fu">set_na</span>(., <span class="at">na =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">999</span>, <span class="sc">-</span><span class="dv">888</span>, <span class="sc">-</span><span class="dv">777</span>, <span class="sc">-</span><span class="dv">666</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="revision-de-eliminación-na" class="level3">
<h3 class="anchored" data-anchor-id="revision-de-eliminación-na">Revision de eliminación NA</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c05_01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Grado de confianza: El Gobierno (x) &lt;numeric&gt; 
# total N=1222 valid N=1217 mean=2.09 sd=1.02

Value |    Label |   N | Raw % | Valid % | Cum. %
-------------------------------------------------
    1 |     Nada | 428 | 35.02 |   35.17 |  35.17
    2 |     Poca | 380 | 31.10 |   31.22 |  66.39
    3 |     Algo | 304 | 24.88 |   24.98 |  91.37
    4 | Bastante |  79 |  6.46 |    6.49 |  97.86
    5 |    Mucha |  26 |  2.13 |    2.14 | 100.00
 &lt;NA&gt; |     &lt;NA&gt; |   5 |  0.41 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c05_02)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Grado de confianza: Los Partidos Politicos (x) &lt;numeric&gt; 
# total N=1222 valid N=1211 mean=1.46 sd=0.74

Value |    Label |   N | Raw % | Valid % | Cum. %
-------------------------------------------------
    1 |     Nada | 808 | 66.12 |   66.72 |  66.72
    2 |     Poca | 273 | 22.34 |   22.54 |  89.27
    3 |     Algo | 114 |  9.33 |    9.41 |  98.68
    4 | Bastante |  11 |  0.90 |    0.91 |  99.59
    5 |    Mucha |   5 |  0.41 |    0.41 | 100.00
 &lt;NA&gt; |     &lt;NA&gt; |  11 |  0.90 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c05_07)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Grado de confianza: El Congreso Nacional (x) &lt;numeric&gt; 
# total N=1222 valid N=1214 mean=1.87 sd=0.92

Value |    Label |   N | Raw % | Valid % | Cum. %
-------------------------------------------------
    1 |     Nada | 525 | 42.96 |   43.25 |  43.25
    2 |     Poca | 392 | 32.08 |   32.29 |  75.54
    3 |     Algo | 246 | 20.13 |   20.26 |  95.80
    4 | Bastante |  36 |  2.95 |    2.97 |  98.76
    5 |    Mucha |  15 |  1.23 |    1.24 | 100.00
 &lt;NA&gt; |     &lt;NA&gt; |   8 |  0.65 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c05_08)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Grado de confianza: El Presidente/a de la Republica (x) &lt;numeric&gt; 
# total N=1222 valid N=1020 mean=2.14 sd=1.18

Value |    Label |   N | Raw % | Valid % | Cum. %
-------------------------------------------------
    1 |     Nada | 417 | 34.12 |   40.88 |  40.88
    2 |     Poca | 223 | 18.25 |   21.86 |  62.75
    3 |     Algo | 239 | 19.56 |   23.43 |  86.18
    4 | Bastante |  99 |  8.10 |    9.71 |  95.88
    5 |    Mucha |  42 |  3.44 |    4.12 | 100.00
 &lt;NA&gt; |     &lt;NA&gt; | 202 | 16.53 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c13)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Interes en la politica (x) &lt;numeric&gt; 
# total N=1222 valid N=1221 mean=2.01 sd=1.18

Value |               Label |   N | Raw % | Valid % | Cum. %
------------------------------------------------------------
    1 |     Nada interesado | 573 | 46.89 |   46.93 |  46.93
    2 |     Poco interesado | 276 | 22.59 |   22.60 |  69.53
    3 |     Algo interesado | 209 | 17.10 |   17.12 |  86.65
    4 | Bastante interesado | 111 |  9.08 |    9.09 |  95.74
    5 |      Muy interesado |  52 |  4.26 |    4.26 | 100.00
 &lt;NA&gt; |                &lt;NA&gt; |   1 |  0.08 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c38)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Extension de corrupcion politica (x) &lt;numeric&gt; 
# total N=1222 valid N=1203 mean=4.23 sd=0.92

Value |              Label |   N | Raw % | Valid % | Cum. %
-----------------------------------------------------------
    1 |     Nada extendida |  25 |  2.05 |    2.08 |   2.08
    2 |     Poco extendida |  47 |  3.85 |    3.91 |   5.99
    3 |     Algo extendida | 108 |  8.84 |    8.98 |  14.96
    4 | Bastante extendida | 464 | 37.97 |   38.57 |  53.53
    5 |      Muy extendida | 559 | 45.74 |   46.47 | 100.00
 &lt;NA&gt; |               &lt;NA&gt; |  19 |  1.55 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>c01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Satisfaccion con la democracia en Chile (x) &lt;numeric&gt; 
# total N=1222 valid N=1195 mean=2.14 sd=1.02

Value |               Label |   N | Raw % | Valid % | Cum. %
------------------------------------------------------------
    1 |     Nada satisfecho | 395 | 32.32 |   33.05 |  33.05
    2 |     Poco satisfecho | 372 | 30.44 |   31.13 |  64.18
    3 |     Algo satisfecho | 311 | 25.45 |   26.03 |  90.21
    4 | Bastante satisfecho |  97 |  7.94 |    8.12 |  98.33
    5 |      Muy satisfecho |  20 |  1.64 |    1.67 | 100.00
 &lt;NA&gt; |                &lt;NA&gt; |  27 |  2.21 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>sexo_enc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sexo del encuestador/a (x) &lt;numeric&gt; 
# total N=1222 valid N=995 mean=1.70 sd=0.46

Value |  Label |   N | Raw % | Valid % | Cum. %
-----------------------------------------------
    1 | Hombre | 302 | 24.71 |   30.35 |  30.35
    2 |  Mujer | 693 | 56.71 |   69.65 | 100.00
 &lt;NA&gt; |   &lt;NA&gt; | 227 | 18.58 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>edad_enc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Edad del encuestador/a (x) &lt;numeric&gt; 
# total N=1222 valid N=1222 mean=26.54 sd=2.90

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
   19 |  19 |  1.55 |    1.55 |   1.55
   20 |  40 |  3.27 |    3.27 |   4.83
   21 |   9 |  0.74 |    0.74 |   5.56
   22 | 121 |  9.90 |    9.90 |  15.47
   23 |  13 |  1.06 |    1.06 |  16.53
   24 |  62 |  5.07 |    5.07 |  21.60
   25 | 110 |  9.00 |    9.00 |  30.61
   26 | 156 | 12.77 |   12.77 |  43.37
   27 | 138 | 11.29 |   11.29 |  54.66
   28 | 129 | 10.56 |   10.56 |  65.22
   29 | 258 | 21.11 |   21.11 |  86.33
   30 | 167 | 13.67 |   13.67 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
</section>
<section id="visualizar-nombres" class="level3">
<h3 class="anchored" data-anchor-id="visualizar-nombres">Visualizar nombres</h3>
<p>Para una mejor fundamentación, en el presente estudio se emplearán 7 variables del total de datos que brinda ELSOC. En donde las variables a trabajar constan de: Grado de confianza en el gobierno, Grado de confianza en Los Partidos Políticos, Grado de Confianza en El Congreso Nacional. Ambas tres variables forman parte de un analisis del grado de confianza con las 3 instituciones politicas mas importantes de la democracia Chilena representativa. Ademas, de igual manera se utilizara la variable que se relaciona conforme al interes que tienen las personas en la Politica en general, asi como tambien la percepción de estos mismos con la corrupción politica. En ese sentido tambien se empleara el tipo sexo de la persona y su respectiva edad del encuestado.</p>
<p>Variables que nos serviran para lograr entender si realmente existe una alto indice de desconfianza en la institucionalidad politica, pudiendo analizar cual es el relacionamiento con el andamiaje politico entre personas en un rango etario mas joven, y segmentadas por sexo hombre/mujer.</p>
<p>Primero, es importante visualizar los nombres de las variables para indagar en ellas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(proc_data_fil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "c05_01"   "c05_02"   "c05_07"   "c05_08"   "c13"      "c38"     
 [7] "c01"      "sexo_enc" "m01"      "edad_enc"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_label</span>(proc_data_fil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                               c05_01 
                    "Grado de confianza: El Gobierno" 
                                               c05_02 
         "Grado de confianza: Los Partidos Politicos" 
                                               c05_07 
           "Grado de confianza: El Congreso Nacional" 
                                               c05_08 
"Grado de confianza: El Presidente/a de la Republica" 
                                                  c13 
                             "Interes en la politica" 
                                                  c38 
                   "Extension de corrupcion politica" 
                                                  c01 
            "Satisfaccion con la democracia en Chile" 
                                             sexo_enc 
                             "Sexo del encuestador/a" 
                                                  m01 
                                  "Nivel educacional" 
                                             edad_enc 
                             "Edad del encuestador/a" </code></pre>
</div>
</div>
<p>Modificamos los nombres de las variables para un mejor entendimiento y una mayor claridad lectiva de estas mismas variables empleadas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil <span class="ot">&lt;-</span> proc_data_fil <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"conf_gob"</span><span class="ot">=</span>c05_01, <span class="co"># Confianza gobierno</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"conf_partpol"</span><span class="ot">=</span>c05_02, <span class="co"># Confianza partidos politicos</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"conf_cong"</span><span class="ot">=</span>c05_07, <span class="co"># Confianza Congreso Nacional</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"conf_pres"</span><span class="ot">=</span>c05_08, <span class="co">#Confianza Presidente R.</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"legt_pol"</span><span class="ot">=</span>c13, <span class="co"># Legitimación Politica</span></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"percp_corrup"</span><span class="ot">=</span>c38,<span class="co">#Percepción Corrupción Politica</span></span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"Nivel_educ"</span><span class="ot">=</span> m01,</span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>                                          <span class="st">"actitud_demo"</span><span class="ot">=</span>c01) <span class="co">#Actitud hacia democracia</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_gob <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>conf_gob,<span class="at">label =</span> <span class="st">"Confianza: Gobierno"</span>)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>conf_gob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confianza: Gobierno"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_partpol <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>conf_partpol,<span class="at">label =</span> <span class="st">"Confianza: P.Politico"</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>conf_partpol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confianza: P.Politico"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_cong <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>conf_cong,<span class="at">label =</span> <span class="st">"Confianza: Congreso"</span>)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>conf_cong)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confianza: Congreso"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_pres <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>conf_pres,<span class="at">label =</span> <span class="st">"Confianza: Presidente"</span>)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>conf_pres)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confianza: Presidente"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>legt_pol <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>legt_pol,<span class="at">label =</span> <span class="st">"Legitimación: Politica"</span>)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>legt_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Legitimación: Politica"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>percp_corrup <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>percp_corrup,<span class="at">label =</span> <span class="st">"Percepcion: Corrupcion"</span>)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>percp_corrup)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Percepcion: Corrupcion"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>actitud_demo <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>actitud_demo,<span class="at">label =</span> <span class="st">"Actitud: Democracia"</span>)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>actitud_demo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Actitud: Democracia"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>Nivel_educ <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data_fil<span class="sc">$</span>Nivel_educ,<span class="at">label =</span> <span class="st">"Nivel: educacional"</span>)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data_fil<span class="sc">$</span>Nivel_educ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Nivel: educacional"</code></pre>
</div>
</div>
</section>
<section id="obtener-datos-descriptivos" class="level3">
<h3 class="anchored" data-anchor-id="obtener-datos-descriptivos">Obtener datos descriptivos</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(proc_data_fil)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(proc_data_fil, <span class="at">type=</span><span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
==========================================
Statistic      N    Mean  St. Dev. Min Max
------------------------------------------
conf_gob     1,217 2.092   1.023    1   5 
conf_partpol 1,211 1.457   0.735    1   5 
conf_cong    1,214 1.867   0.921    1   5 
conf_pres    1,020 2.143   1.176    1   5 
legt_pol     1,221 2.011   1.178    1   5 
percp_corrup 1,203 4.234   0.918    1   5 
actitud_demo 1,195 2.142   1.023    1   5 
sexo_enc      995  1.696   0.460    1   2 
Nivel_educ   1,220 5.432   2.205    1  10 
edad_enc     1,222 26.543  2.904   19  30 
------------------------------------------</code></pre>
</div>
</div>
<p>En estas tablas, a simple vista podemos visualizar los casos que se encuentran en cada respectiva variable, en donde se adjunta en cada variable su respectivo valor, su nombre, la media, la desviación estándar, y el rango de respuesta que tuvo cada variable por sí sola. En mayor detalle no indagaremos ya que posteriomente adentrarnos en un analisis mas profundo. Sin embargo, a muy grandes rasgos se puede decir que la cantidad de observación es por cada variable, aproximadamente oscila entre 1204 y 1221, en donde la confianza en en los partidos políticos representa la media más baja de las 3 instituciones a analizar adquiriendo un valor de 1.457, mientras que es seguida por la confianza en el Congreso Nacional que tuvo un valor de 1.866. Por su parte la mayor confianza de estas instituciones la tiene el Gobierno, adscribiendo como promedio la categoría de respuesta Poca desconfianza. Ademas, la cateogria de legitimacion politica en relación al interes por esta, adquiere valores entorno a una categoria de poco interes en la politica.</p>
<p>Fundamentalmente, otro valor importante a destacar hace referencia con la alta percepción de corrupción que existe entre los datos analizados, que apelan a la percepción de una alta corrupcion extendida en la politica, teniendo una media de 4.23 en una categoria de respuesta donde el valor mas alto es 5 (Muy extendida).</p>
<p>En resumen, la tabla proporciona información sobre la confianza en diferentes aspectos del gobierno y la política, así como sobre la legitimación política y la percepción de la corrupción. Las medias y desviaciones estándar muestran cómo varían estas medidas entre la población estudiada, mientras que los intervalos de confianza indican la incertidumbre asociada con estas estimaciones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>summarytools<span class="sc">::</span><span class="fu">dfSummary</span>(proc_data_fil, <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>### Data Frame Summary  
#### proc_data_fil  
**Dimensions:** 1222 x 10  
**Duplicates:** 24  

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
No   Variable                               Label                    Stats / Values            Freqs (% of Valid)   Graph                                    Valid      Missing  
---- -------------------------------------- ------------------------ ------------------------- -------------------- ---------------------------------------- ---------- ---------
1    conf_gob\                              Confianza: Gobierno      Mean (sd) : 2.1 (1)\      1 : 428 (35.2%)\     IIIIIII \                                1217\      5\       
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 380 (31.2%)\     IIIIII \                                 (99.6%)    (0.4%)   
                                                                     1 &lt; 2 &lt; 5\                3 : 304 (25.0%)\     IIII \                                                       
                                                                     IQR (CV) : 2 (0.5)        4 :  79 ( 6.5%)\     I \                                                          
                                                                                               5 :  26 ( 2.1%)                                                                   

2    conf_partpol\                          Confianza: P.Politico    Mean (sd) : 1.5 (0.7)\    1 : 808 (66.7%)\     IIIIIIIIIIIII \                          1211\      11\      
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 273 (22.5%)\     IIII \                                   (99.1%)    (0.9%)   
                                                                     1 &lt; 1 &lt; 5\                3 : 114 ( 9.4%)\     I \                                                          
                                                                     IQR (CV) : 1 (0.5)        4 :  11 ( 0.9%)\     \                                                            
                                                                                               5 :   5 ( 0.4%)                                                                   

3    conf_cong\                             Confianza: Congreso      Mean (sd) : 1.9 (0.9)\    1 : 525 (43.2%)\     IIIIIIII \                               1214\      8\       
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 392 (32.3%)\     IIIIII \                                 (99.3%)    (0.7%)   
                                                                     1 &lt; 2 &lt; 5\                3 : 246 (20.3%)\     IIII \                                                       
                                                                     IQR (CV) : 1 (0.5)        4 :  36 ( 3.0%)\     \                                                            
                                                                                               5 :  15 ( 1.2%)                                                                   

4    conf_pres\                             Confianza: Presidente    Mean (sd) : 2.1 (1.2)\    1 : 417 (40.9%)\     IIIIIIII \                               1020\      202\     
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 223 (21.9%)\     IIII \                                   (83.5%)    (16.5%)  
                                                                     1 &lt; 2 &lt; 5\                3 : 239 (23.4%)\     IIII \                                                       
                                                                     IQR (CV) : 2 (0.5)        4 :  99 ( 9.7%)\     I \                                                          
                                                                                               5 :  42 ( 4.1%)                                                                   

5    legt_pol\                              Legitimación: Politica   Mean (sd) : 2 (1.2)\      1 : 573 (46.9%)\     IIIIIIIII \                              1221\      1\       
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 276 (22.6%)\     IIII \                                   (99.9%)    (0.1%)   
                                                                     1 &lt; 2 &lt; 5\                3 : 209 (17.1%)\     III \                                                        
                                                                     IQR (CV) : 2 (0.6)        4 : 111 ( 9.1%)\     I \                                                          
                                                                                               5 :  52 ( 4.3%)                                                                   

6    percp_corrup\                          Percepcion: Corrupcion   Mean (sd) : 4.2 (0.9)\    1 :  25 ( 2.1%)\     \                                        1203\      19\      
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 :  47 ( 3.9%)\     \                                        (98.4%)    (1.6%)   
                                                                     1 &lt; 4 &lt; 5\                3 : 108 ( 9.0%)\     I \                                                          
                                                                     IQR (CV) : 1 (0.2)        4 : 464 (38.6%)\     IIIIIII \                                                    
                                                                                               5 : 559 (46.5%)      IIIIIIIII                                                    

7    actitud_demo\                          Actitud: Democracia      Mean (sd) : 2.1 (1)\      1 : 395 (33.1%)\     IIIIII \                                 1195\      27\      
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 372 (31.1%)\     IIIIII \                                 (97.8%)    (2.2%)   
                                                                     1 &lt; 2 &lt; 5\                3 : 311 (26.0%)\     IIIII \                                                      
                                                                     IQR (CV) : 2 (0.5)        4 :  97 ( 8.1%)\     I \                                                          
                                                                                               5 :  20 ( 1.7%)                                                                   

8    sexo_enc\                              Sexo del encuestador/a   Min  : 1\                 1 : 302 (30.4%)\     IIIIII \                                 995\       227\     
     [haven_labelled, vctrs_vctr, double]                            Mean : 1.7\               2 : 693 (69.6%)      IIIIIIIIIIIII                            (81.4%)    (18.6%)  
                                                                     Max  : 2                                                                                                    

9    Nivel_educ\                            Nivel: educacional       Mean (sd) : 5.4 (2.2)\    1 :   5 ( 0.4%)\     \                                        1220\      2\       
     [haven_labelled, vctrs_vctr, double]                            min &lt; med &lt; max:\         2 : 135 (11.1%)\     II \                                     (99.8%)    (0.2%)   
                                                                     1 &lt; 5 &lt; 10\               3 : 107 ( 8.8%)\     I \                                                          
                                                                     IQR (CV) : 3 (0.4)        4 : 151 (12.4%)\     II \                                                         
                                                                                               5 : 361 (29.6%)\     IIIII \                                                      
                                                                                               6 :  36 ( 3.0%)\     \                                                            
                                                                                               7 : 174 (14.3%)\     II \                                                         
                                                                                               8 :  87 ( 7.1%)\     I \                                                          
                                                                                               9 : 148 (12.1%)\     II \                                                         
                                                                                               10 :  16 ( 1.3%)                                                                  

10   edad_enc\                              Edad del encuestador/a   Mean (sd) : 26.5 (2.9)\   12 distinct values   \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\   1222\      0\       
     [numeric]                                                       min &lt; med &lt; max:\                              \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\   (100.0%)   (0.0%)   
                                                                     19 &lt; 27 &lt; 30\                                  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\                       
                                                                     IQR (CV) : 4 (0.1)                             \ \ \ \ . \ \ \ \ . : . . :\                                 
                                                                                                                    . \ \ : \ \ . : : : : :                                      
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>En esta tabla, a modo particular podemos indagar en una aproximación de lo que vendría siendo la distribución de cada variable. Aquí, ya podemos realizar un análisis en profundidad, en donde en primera instancia se observa que el grado de confianza en la institución de gobierno es bajísima, pero siendo la que relativamente genera más confianza en la población de estudio. Por su parte, la institucionalidad de los partidos políticos es sobre quien más recae el cuestionamiento sobre la desconfianza, obteniendo esta variable la peor evaluación. El congreso nacional, también tiene un bajo nivel de desconfianza, siendo un poco más baja la desconfianza que la institución de gobierno como tal. En cuanto al interés en la política, se deja a entrever a grandes rasgos que la población joven, prácticamente en más de un 50% no tiene mayor interés en esta perspectiva. Por último, en cuanto a la percepción de corrupción política que presenta el rango etario de 18 a 30 años, nos expresa que la mayor parte de esta población siente que la corrupción política se encuentra entre algo extendida y muy extendida en nuestro país.</p>
</section>
<section id="tablas-de-contigencia" class="level3">
<h3 class="anchored" data-anchor-id="tablas-de-contigencia">Tablas de contigencia</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(proc_data_fil<span class="sc">$</span>legt_pol, proc_data_fil<span class="sc">$</span>sexo_enc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Legitimación:<br>Politica</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">Sexo del<br>encuestador/a</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Hombre</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Mujer</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Nada interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">134</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">321</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">455</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Poco interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">73</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">163</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">236</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Algo interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">54</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">117</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">171</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Bastante interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">28</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">62</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">90</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Muy interesado</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">12</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">30</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">42</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">301</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">693</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">994</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">χ<sup>2</sup>=0.420 · df=4 · Cramer's V=0.021 · p=0.981</td> 
</tr>
 
</tbody></table>
</div>
</div>
<p>En esta tabla podemos ejemplificar la legitimacion politica en relación a una clara distinción entre sexos, en donde se deja a entrever que son en mayor medida la categoría de nada interesado en la política se retrae a la mayor cantidad de respuestas estipuladas, en donde también se deja a entrever una mayor cantidad de mujeres quienes respondieron la encuesta del total de la población encuestada. En ese sentido la mayor cantidad de respuestas en ambos sexos se concentra en la categoría ya mencionada, afirmando que aprox. mas del 50% de los encuestados afirma no estar nada interesado en política.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(proc_data_fil<span class="sc">$</span>percp_corrup, proc_data_fil<span class="sc">$</span>sexo_enc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Percepcion:<br>Corrupcion</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">Sexo del<br>encuestador/a</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Hombre</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Mujer</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Nada extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">6</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">14</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">20</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Poco extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">13</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">28</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">41</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Algo extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">23</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">67</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">90</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Bastante extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">116</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">272</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">388</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Muy extendida</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">138</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">306</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">444</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">296</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">687</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">983</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">χ<sup>2</sup>=1.144 · df=4 · Cramer's V=0.034 · p=0.887</td> 
</tr>
 
</tbody></table>
</div>
</div>
<p>De igual manera, en relacion a la tabla de contingencia sobre la precepcion de corrupción se observa que gran cantidad de la poblacion total encuestada (ya sea hombre o mujer) afirma que la corrupción politica se encuentra bastante o muy extendida en nuestro pais, siendo un claro indice de una falta de seriedad y profesinalismo en materia politica debido al actuar de estos sujetos gubernamentales.</p>
</section>
<section id="tablas-con-porcentajes" class="level3">
<h3 class="anchored" data-anchor-id="tablas-con-porcentajes">Tablas con porcentajes</h3>
<p>Para mas detalles adjuntamos la realizacion de las mismas tables anteriormente estipulados, pero con la expecion de un analisis en porcentajes para un estudio mas detallado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(proc_data_fil<span class="sc">$</span>percp_corrup, proc_data_fil<span class="sc">$</span>edad_enc,</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.col.prc=</span><span class="cn">TRUE</span>,</span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.summary=</span><span class="cn">FALSE</span>,</span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">encoding =</span> <span class="st">"UTF-8"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">Percepcion:<br>
Corrupcion</td>
<td colspan="12" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">Edad del<br>
encuestador/a</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">19</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">20</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">21</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">22</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">23</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">24</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">25</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">26</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">27</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">28</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">29</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">30</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Nada extendida</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">1</span><br>
<span style="color:#339933;">5.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">0</span><br>
<span style="color:#339933;">0&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">0</span><br>
<span style="color:#339933;">0&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">6</span><br>
<span style="color:#339933;">5.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">0</span><br>
<span style="color:#339933;">0&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">1</span><br>
<span style="color:#339933;">1.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">0</span><br>
<span style="color:#339933;">0&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">3</span><br>
<span style="color:#339933;">2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2</span><br>
<span style="color:#339933;">1.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">1</span><br>
<span style="color:#339933;">0.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">9</span><br>
<span style="color:#339933;">3.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2</span><br>
<span style="color:#339933;">1.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">25</span><br>
<span style="color:#339933;">2.1&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Poco extendida</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">1</span><br>
<span style="color:#339933;">5.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">1</span><br>
<span style="color:#339933;">2.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">1</span><br>
<span style="color:#339933;">11.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4</span><br>
<span style="color:#339933;">3.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">0</span><br>
<span style="color:#339933;">0&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">0</span><br>
<span style="color:#339933;">0&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">6</span><br>
<span style="color:#339933;">5.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">11</span><br>
<span style="color:#339933;">7.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">3</span><br>
<span style="color:#339933;">2.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4</span><br>
<span style="color:#339933;">3.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">9</span><br>
<span style="color:#339933;">3.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">7</span><br>
<span style="color:#339933;">4.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">47</span><br>
<span style="color:#339933;">3.9&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Algo extendida</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4</span><br>
<span style="color:#339933;">21.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2</span><br>
<span style="color:#339933;">5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">0</span><br>
<span style="color:#339933;">0&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">10</span><br>
<span style="color:#339933;">8.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2</span><br>
<span style="color:#339933;">15.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2</span><br>
<span style="color:#339933;">3.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">21</span><br>
<span style="color:#339933;">19.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">10</span><br>
<span style="color:#339933;">6.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">14</span><br>
<span style="color:#339933;">10.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">12</span><br>
<span style="color:#339933;">9.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">26</span><br>
<span style="color:#339933;">10.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">5</span><br>
<span style="color:#339933;">3.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">108</span><br>
<span style="color:#339933;">9&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Bastante extendida</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">8</span><br>
<span style="color:#339933;">42.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">14</span><br>
<span style="color:#339933;">35&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">6</span><br>
<span style="color:#339933;">66.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">41</span><br>
<span style="color:#339933;">34.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">5</span><br>
<span style="color:#339933;">38.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">18</span><br>
<span style="color:#339933;">29&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">51</span><br>
<span style="color:#339933;">46.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">55</span><br>
<span style="color:#339933;">36.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">60</span><br>
<span style="color:#339933;">44.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">42</span><br>
<span style="color:#339933;">32.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">108</span><br>
<span style="color:#339933;">41.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">56</span><br>
<span style="color:#339933;">34.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">464</span><br>
<span style="color:#339933;">38.6&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Muy extendida</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">5</span><br>
<span style="color:#339933;">26.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">23</span><br>
<span style="color:#339933;">57.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2</span><br>
<span style="color:#339933;">22.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">57</span><br>
<span style="color:#339933;">48.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">6</span><br>
<span style="color:#339933;">46.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">41</span><br>
<span style="color:#339933;">66.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">31</span><br>
<span style="color:#339933;">28.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">71</span><br>
<span style="color:#339933;">47.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">57</span><br>
<span style="color:#339933;">41.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">69</span><br>
<span style="color:#339933;">53.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">106</span><br>
<span style="color:#339933;">41.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">91</span><br>
<span style="color:#339933;">56.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">559</span><br>
<span style="color:#339933;">46.5&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">19</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">40</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">9</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">118</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">13</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">62</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">109</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">150</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">136</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">128</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">258</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">161</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">1203</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Aqui, en esta tabla con porcentajes observamos que entre las personas de 18 a 30 años, tan solo el 2,1%, es decir, 25 personas, comsiderar que la percepción de corrupcion politica se encuentra para Nada extendida en nuestro pais, de un total de 1203 encuestados. Por el contrario, de esos 1203 personas jovenes de entre 18 a 30 años, un ttoal de 559, es decir, cerca de la mitad de los encuestados (46,5%) afirma expresamente que la corrupción politica se encuentra muy extendida.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(proc_data_fil<span class="sc">$</span>legt_pol, proc_data_fil<span class="sc">$</span>sexo_enc,</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.col.prc=</span><span class="cn">TRUE</span>,</span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.summary=</span><span class="cn">FALSE</span>,</span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">encoding =</span> <span class="st">"UTF-8"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">Legitimación:<br>
Politica</td>
<td colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">Sexo del<br>
encuestador/a</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Hombre</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mujer</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Nada interesado</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">134</span><br>
<span style="color:#339933;">44.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">321</span><br>
<span style="color:#339933;">46.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">455</span><br>
<span style="color:#339933;">45.8&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Poco interesado</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">73</span><br>
<span style="color:#339933;">24.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">163</span><br>
<span style="color:#339933;">23.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">236</span><br>
<span style="color:#339933;">23.7&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Algo interesado</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">54</span><br>
<span style="color:#339933;">17.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">117</span><br>
<span style="color:#339933;">16.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">171</span><br>
<span style="color:#339933;">17.2&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Bastante interesado</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">28</span><br>
<span style="color:#339933;">9.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">62</span><br>
<span style="color:#339933;">8.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">90</span><br>
<span style="color:#339933;">9.1&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Muy interesado</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">12</span><br>
<span style="color:#339933;">4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">30</span><br>
<span style="color:#339933;">4.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">42</span><br>
<span style="color:#339933;">4.2&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">301</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">693</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">994</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>En relacion a esta tabla se identifica que en promedio es casi el mismo porcentaje de hombres y mujeres que no se encuentran para nada interesadoas en la politica institucional de nuestro pais. Ademas, tambien se del total de encuestados, entre hombres y mujeres,, un 4,2% expresa que se encuentra muy interesado en la politica. Se expresa que no hay diferencias claramente significativas entre ambos generos en relacion a la variable de legitimación politica. De igual manera es importante recalcar que las diferencias en relacio a la cantidad de encuestados, dice relacion con una mayor poblacion femenina en la muestra analisasa en la base de datos de este estudio.</p>
</section>
<section id="graficos" class="level3">
<h3 class="anchored" data-anchor-id="graficos">Graficos</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> legt_pol)) <span class="sc">+</span> </span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"coral"</span>)<span class="sc">+</span></span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Grado de percepción de legitimación politica"</span>,</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Percepción de Legitimación Politica"</span>,</span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TRABAJO4RRRRRRR_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Con base en los datos proporcionados, es evidente que existe una baja percepción de legitimación política en Chile. Esto se refleja en los niveles de interés político de la población, donde la mayoría de los encuestados se encuentran en las categorías de “Nada interesado” y “Poco interesado”, representando el 45% y el 24% respectivamente. El nivel de interés político aumenta gradualmente a medida que avanzamos hacia las categorías de “Algo interesado”, “Bastante interesado” y “Muy interesado”, con porcentajes significativamente menores en comparación con los niveles de desinterés. Esto sugiere que una parte sustancial de la población chilena no se siente involucrada o comprometida con la política, lo que puede tener implicaciones negativas para la legitimidad y la estabilidad del sistema político.</p>
<p>Esta baja percepción de legitimación política puede estar relacionada con una serie de factores, como la falta de representatividad de las instituciones políticas, la corrupción, la desigualdad socioeconómica o la percepción de que las acciones del gobierno no satisfacen las necesidades y demandas de la población.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> percp_corrup)) <span class="sc">+</span> </span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"coral"</span>)<span class="sc">+</span></span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Grado de percepción de corrupción  politica"</span>,</span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Percepción de corrupción Politica"</span>,</span>
<span id="cb117-5"><a href="#cb117-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 19 rows containing non-finite outside the scale range
(`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TRABAJO4RRRRRRR_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En relacion a los datos obtenidos se observa una alta percepción de corrupción política en Chile en la pobalcion joven que ronda los 18 a 30 años. La mayoría de los encuestados perciben la corrupción como un problema significativo y que pareciera esta al latir de la sociedad chilena, en donde en un aproximado, mas de un 70% de esta poblacion de estudio indica que la corrupción en nuestro pais se encuentra entre “Bastante extendida” y “Muy extendida”. Afirmando de esta manera lo que en un principio se tenia como hipotesis de trabajo, que era que la poblacion joven, vale decir, la poblacion objetivo de este estudio, expresan altos estandares de malversación en el actuar politico, ya sea por diversos motivos.</p>
<p>En generla, se puede afirmar que la indagacion en estos datos sugieren que la corrupción política es un tema de gran preocupación para la población chilena joven, lo que puede tener consecuencias negativas para la confianza en las instituciones gubernamentales y para la legitimidad del sistema político de la democracia chilena en su conjunto.</p>
</section>
<section id="re-etiquetar-los-valores" class="level3">
<h3 class="anchored" data-anchor-id="re-etiquetar-los-valores">Re-etiquetar los valores</h3>
<p>En este punto, se vuelve fundamental que para la continuidad de la investigacion se realice un reetiquetado de las variables y sus respectivos valores que le corresponden para asi dar paso, -mas adelante-, a la creacion de una escala en relacion a al confianza institucional politica en relacion a la fundamentacion de las variables de confianza en: Gobierno, Partidos Politicos, Congreso Nacional y Presidente de la República.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_gob <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>conf_gob, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_partpol <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>conf_partpol, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_cong <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>conf_cong, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_pres <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data_fil<span class="sc">$</span>conf_pres, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Aqui, para la continuidad de los propios fines investigativos generamos y le asignamos nuevos valores a las variables, conforme a suscategorias de respuesta que ahora van entre 0 y 4 respectivamente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_gob <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data_fil<span class="sc">$</span>conf_gob,</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Nada de confianza"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Poca confianza"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Algo de confianza"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb120-5"><a href="#cb120-5" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Bastante confianza"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb120-6"><a href="#cb120-6" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Mucha confianza"</span><span class="ot">=</span><span class="dv">4</span>))</span>
<span id="cb120-7"><a href="#cb120-7" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_partpol <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data_fil<span class="sc">$</span>conf_partpol,</span>
<span id="cb120-8"><a href="#cb120-8" aria-hidden="true" tabindex="-1"></a>                              <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Nada de confianza"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb120-9"><a href="#cb120-9" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Poca confianza"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb120-10"><a href="#cb120-10" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Algo de confianza"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb120-11"><a href="#cb120-11" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Bastante confianza"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb120-12"><a href="#cb120-12" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Mucha confianza"</span><span class="ot">=</span><span class="dv">4</span>))</span>
<span id="cb120-13"><a href="#cb120-13" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_cong <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data_fil<span class="sc">$</span>conf_cong,</span>
<span id="cb120-14"><a href="#cb120-14" aria-hidden="true" tabindex="-1"></a>                              <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Nada de confianza"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb120-15"><a href="#cb120-15" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Poca confianza"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb120-16"><a href="#cb120-16" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Algo de confianza"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb120-17"><a href="#cb120-17" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Bastante confianza"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb120-18"><a href="#cb120-18" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Mucha confianza"</span><span class="ot">=</span><span class="dv">4</span>))</span>
<span id="cb120-19"><a href="#cb120-19" aria-hidden="true" tabindex="-1"></a>proc_data_fil<span class="sc">$</span>conf_pres <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data_fil<span class="sc">$</span>conf_pres,</span>
<span id="cb120-20"><a href="#cb120-20" aria-hidden="true" tabindex="-1"></a>                              <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Nada de confianza"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb120-21"><a href="#cb120-21" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Poca confianza"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb120-22"><a href="#cb120-22" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Algo de confianza"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb120-23"><a href="#cb120-23" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Bastante confianza"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb120-24"><a href="#cb120-24" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Mucha confianza"</span><span class="ot">=</span><span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Aqui comprobamos con el codigo frq de que realmente las variables hayan quedado con categorias de respuestas que fluctuan entre 0, 1 ,2, 3 y 4 respectivamente para la creación de la escala.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>conf_gob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confianza: Gobierno (x) &lt;numeric&gt; 
# total N=1222 valid N=1217 mean=1.09 sd=1.02

Value |              Label |   N | Raw % | Valid % | Cum. %
-----------------------------------------------------------
    0 |  Nada de confianza | 428 | 35.02 |   35.17 |  35.17
    1 |     Poca confianza | 380 | 31.10 |   31.22 |  66.39
    2 |  Algo de confianza | 304 | 24.88 |   24.98 |  91.37
    3 | Bastante confianza |  79 |  6.46 |    6.49 |  97.86
    4 |    Mucha confianza |  26 |  2.13 |    2.14 | 100.00
 &lt;NA&gt; |               &lt;NA&gt; |   5 |  0.41 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>conf_partpol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confianza: P.Politico (x) &lt;numeric&gt; 
# total N=1222 valid N=1211 mean=0.46 sd=0.74

Value |              Label |   N | Raw % | Valid % | Cum. %
-----------------------------------------------------------
    0 |  Nada de confianza | 808 | 66.12 |   66.72 |  66.72
    1 |     Poca confianza | 273 | 22.34 |   22.54 |  89.27
    2 |  Algo de confianza | 114 |  9.33 |    9.41 |  98.68
    3 | Bastante confianza |  11 |  0.90 |    0.91 |  99.59
    4 |    Mucha confianza |   5 |  0.41 |    0.41 | 100.00
 &lt;NA&gt; |               &lt;NA&gt; |  11 |  0.90 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>conf_cong)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confianza: Congreso (x) &lt;numeric&gt; 
# total N=1222 valid N=1214 mean=0.87 sd=0.92

Value |              Label |   N | Raw % | Valid % | Cum. %
-----------------------------------------------------------
    0 |  Nada de confianza | 525 | 42.96 |   43.25 |  43.25
    1 |     Poca confianza | 392 | 32.08 |   32.29 |  75.54
    2 |  Algo de confianza | 246 | 20.13 |   20.26 |  95.80
    3 | Bastante confianza |  36 |  2.95 |    2.97 |  98.76
    4 |    Mucha confianza |  15 |  1.23 |    1.24 | 100.00
 &lt;NA&gt; |               &lt;NA&gt; |   8 |  0.65 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data_fil<span class="sc">$</span>conf_pres)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confianza: Presidente (x) &lt;numeric&gt; 
# total N=1222 valid N=1020 mean=1.14 sd=1.18

Value |              Label |   N | Raw % | Valid % | Cum. %
-----------------------------------------------------------
    0 |  Nada de confianza | 417 | 34.12 |   40.88 |  40.88
    1 |     Poca confianza | 223 | 18.25 |   21.86 |  62.75
    2 |  Algo de confianza | 239 | 19.56 |   23.43 |  86.18
    3 | Bastante confianza |  99 |  8.10 |    9.71 |  95.88
    4 |    Mucha confianza |  42 |  3.44 |    4.12 | 100.00
 &lt;NA&gt; |               &lt;NA&gt; | 202 | 16.53 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
</section>
<section id="correlación-de-las-variables" class="level3">
<h3 class="anchored" data-anchor-id="correlación-de-las-variables">Correlación de las variables</h3>
<p>En el siguiente apartado indagaremos en un analisis que se llevara a cabo entorno a una correlación entre las variables a trabajar en este estudio, para de esta manera intentar lograr examinar las suficientes relaciones entre las diversas variables a trabajar en nuestro conjunto de datos utilizados para los fines de esta investigación.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(proc_data_fil, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>M</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 conf_gob conf_partpol    conf_cong   conf_pres    legt_pol
conf_gob      1.000000000   0.40240754  0.398946516  0.69653159  0.08777666
conf_partpol  0.402407536   1.00000000  0.386657742  0.29818027  0.24502670
conf_cong     0.398946516   0.38665774  1.000000000  0.36677093  0.19220955
conf_pres     0.696531593   0.29818027  0.366770926  1.00000000 -0.02444815
legt_pol      0.087776663   0.24502670  0.192209547 -0.02444815  1.00000000
percp_corrup -0.147861894  -0.18100649 -0.106977584 -0.14773918  0.04108686
actitud_demo  0.402697162   0.32803431  0.351081906  0.31007456  0.14366683
sexo_enc     -0.002705552  -0.01898950 -0.018002085  0.04563824 -0.01989757
Nivel_educ    0.013348818   0.07223204  0.059318524 -0.06432881  0.32850709
edad_enc      0.129707203   0.03620139 -0.006730834  0.09853393 -0.05893992
             percp_corrup actitud_demo     sexo_enc  Nivel_educ     edad_enc
conf_gob     -0.147861894   0.40269716 -0.002705552  0.01334882  0.129707203
conf_partpol -0.181006494   0.32803431 -0.018989498  0.07223204  0.036201387
conf_cong    -0.106977584   0.35108191 -0.018002085  0.05931852 -0.006730834
conf_pres    -0.147739181   0.31007456  0.045638245 -0.06432881  0.098533927
legt_pol      0.041086860   0.14366683 -0.019897573  0.32850709 -0.058939924
percp_corrup  1.000000000  -0.11530578 -0.036544857  0.11469977  0.002391176
actitud_demo -0.115305783   1.00000000 -0.077675198  0.04256739 -0.017250647
sexo_enc     -0.036544857  -0.07767520  1.000000000 -0.00904992  0.128013325
Nivel_educ    0.114699772   0.04256739 -0.009049920  1.00000000 -0.050547061
edad_enc      0.002391176  -0.01725065  0.128013325 -0.05054706  1.000000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_corr</span>(proc_data_fil, </span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">triangle =</span> <span class="st">"lower"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">&nbsp;</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Confianza: Gobierno</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Confianza: P.Politico</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Confianza: Congreso</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Confianza: Presidente</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Legitimación: Politica</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Percepcion: Corrupcion</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Actitud: Democracia</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Sexo del encuestador/a</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Nivel: educacional</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Edad del encuestador/a</td>
</tr>
<tr class="even">
<td style="font-style: italic">Confianza: Gobierno</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Confianza: P.Politico</td>
<td style="text-align: center; padding: 0.2cm;">0.402<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Confianza: Congreso</td>
<td style="text-align: center; padding: 0.2cm;">0.399<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.387<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Confianza: Presidente</td>
<td style="text-align: center; padding: 0.2cm;">0.697<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.298<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.367<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Legitimación: Politica</td>
<td style="text-align: center; padding: 0.2cm;">0.088<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">0.245<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.192<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.024<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Percepcion: Corrupcion</td>
<td style="text-align: center; padding: 0.2cm;">-0.148<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.181<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.107<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.148<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.041<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Actitud: Democracia</td>
<td style="text-align: center; padding: 0.2cm;">0.403<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.328<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.351<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.310<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.144<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.115<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Sexo del encuestador/a</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.003<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.019<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.018<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.046<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.020<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.037<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">-0.078<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Nivel: educacional</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.013<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.072<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.059<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.064<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.329<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.115<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.043<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.009<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Edad del encuestador/a</td>
<td style="text-align: center; padding: 0.2cm;">0.130<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.036<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.007<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.099<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.059<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.002<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.017<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.128<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.051<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td colspan="11" style="text-align: right; border-bottom: double black; border-top: 1px solid black; font-style: italic; font-size: 0.9em;">Computed correlation used pearson-method with listwise-deletion.</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_corr</span>(proc_data_fil, </span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">na.deletion =</span> <span class="st">"pairwise"</span>, <span class="co">#Tratamiento NA</span></span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">triangle =</span> <span class="st">"lower"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">&nbsp;</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Confianza: Gobierno</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Confianza: P.Politico</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Confianza: Congreso</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Confianza: Presidente</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Legitimación: Politica</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Percepcion: Corrupcion</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Actitud: Democracia</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Sexo del encuestador/a</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Nivel: educacional</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">Edad del encuestador/a</td>
</tr>
<tr class="even">
<td style="font-style: italic">Confianza: Gobierno</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Confianza: P.Politico</td>
<td style="text-align: center; padding: 0.2cm;">0.419<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Confianza: Congreso</td>
<td style="text-align: center; padding: 0.2cm;">0.435<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.418<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Confianza: Presidente</td>
<td style="text-align: center; padding: 0.2cm;">0.718<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.311<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.411<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Legitimación: Politica</td>
<td style="text-align: center; padding: 0.2cm;">0.123<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.252<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.157<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.032<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Percepcion: Corrupcion</td>
<td style="text-align: center; padding: 0.2cm;">-0.142<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.163<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.121<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.131<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.032<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Actitud: Democracia</td>
<td style="text-align: center; padding: 0.2cm;">0.440<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.304<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.357<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.363<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.159<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.142<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Sexo del encuestador/a</td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.012<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.003<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.001<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.034<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.010<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.017<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">-0.065<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">Nivel: educacional</td>
<td style="text-align: center; padding: 0.2cm;">0.061<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">0.100<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.054<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.017<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.364<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.124<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.085<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.000<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">Edad del encuestador/a</td>
<td style="text-align: center; padding: 0.2cm;">0.077<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.021<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.003<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">0.062<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.057<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.027<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.003<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.014<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">0.006<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td colspan="11" style="text-align: right; border-bottom: double black; border-top: 1px solid black; font-style: italic; font-size: 0.9em;">Computed correlation used pearson-method with pairwise-deletion.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Para un analisis basado en una mejor claridad, las correlaciones de las variables seran presentadas en un grafico para una revisión en mayor plenitud entorno a un entendimiento mas preciso.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(M)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TRABAJO4RRRRRRR_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A partir de estos datos obtenidos anteriomente, para un analisis a grandes rasgos y breve de los valores mas importantes, podemos decir que se deja a entrever que existe una correlacion positiva significativa entre la confianza en el gobierno y la confianza en la figura del presidente de la republica con un valor de 0.64 afirmando una alta positividad. Asimismo podemos decir que existe una leve correlacion entre la varibale de medicion sobre actitud democractica con las instituciones politicas con valor de 0,41 (Confianza en el Gobobierno), 0,32 (Confianza Partidos Politicos), 0,36 (Confianza Congreso) y 0,32 (Confianza Presidente de la Republica).</p>
</section>
<section id="alpha-de-cronbach" class="level3">
<h3 class="anchored" data-anchor-id="alpha-de-cronbach">Alpha de Cronbach</h3>
<p>Posteriormente indagaremos en el Alpha de Cronbach para observar cual es la relacion del conjunto de variables a trabajar.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data_fil, conf_gob, conf_partpol, conf_cong, conf_pres))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = dplyr::select(proc_data_fil, conf_gob, conf_partpol, 
    conf_cong, conf_pres))

  raw_alpha std.alpha G6(smc) average_r S/N  ase mean   sd median_r
      0.77      0.77    0.75      0.45 3.3 0.01 0.87 0.75     0.42

    95% confidence boundaries 
         lower alpha upper
Feldt     0.75  0.77  0.79
Duhachek  0.75  0.77  0.79

 Reliability if an item is dropped:
             raw_alpha std.alpha G6(smc) average_r S/N alpha se    var.r med.r
conf_gob          0.63      0.65    0.56      0.38 1.8    0.017 0.003580  0.41
conf_partpol      0.77      0.77    0.72      0.52 3.3    0.011 0.029140  0.44
conf_cong         0.74      0.74    0.70      0.48 2.8    0.011 0.044449  0.42
conf_pres         0.68      0.69    0.60      0.42 2.2    0.015 0.000093  0.42

 Item statistics 
                n raw.r std.r r.cor r.drop mean   sd
conf_gob     1217  0.85  0.84  0.81   0.71 1.09 1.02
conf_partpol 1211  0.65  0.70  0.52   0.46 0.46 0.74
conf_cong    1214  0.73  0.74  0.58   0.51 0.87 0.92
conf_pres    1020  0.84  0.79  0.74   0.64 1.14 1.18

Non missing response frequency for each item
                0    1    2    3    4 miss
conf_gob     0.35 0.31 0.25 0.06 0.02 0.00
conf_partpol 0.67 0.23 0.09 0.01 0.00 0.01
conf_cong    0.43 0.32 0.20 0.03 0.01 0.01
conf_pres    0.41 0.22 0.23 0.10 0.04 0.17</code></pre>
</div>
</div>
<p>En general, en ese sentido podemos afirmar que el coeficiente de alfa de Cronbach es de 0,76 lo que nos indica que se presenta un nivel “moderado” a bueno de consistencia interna entre los items de las variables de nuestro trabajo. Por eso se puede expresar que la confiabilidad que evalua la consitencia interna entre las variables nos demuestra que en cierta medida las variables de la escala se corrleacionan entre si con grados altamente positivos sobre una consitencia que se puede decir aceptable para fines propios de este trabajo de investigación.</p>
</section>
<section id="creación-de-escala-de-confianza-en-la-institucionalidad-politica" class="level3">
<h3 class="anchored" data-anchor-id="creación-de-escala-de-confianza-en-la-institucionalidad-politica">Creación de Escala de confianza en la Institucionalidad Politica</h3>
<p>En el ámbito de la democracia chilena, la confianza institucional es un factor fundamental que incide en la estabilidad y el funcionamiento de una sociedad democrática. Es en este contexto, que generamos la creación de una escala con la factiblidad de que nos sirva para evaluar la confianza en instituciones clave como el congreso, el gobierno, los partidos políticos y la figura del presidente de la republica, como parte de una herramienta invaluable para comprender la salud del sistema político chileno. Esta escala, al considerar múltiples variables y su peso relativo, proporciona una visión más completa y precisa de la percepción ciudadana respecto a las instituciones democraticas que conforman el entramado político chileno.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a>proc_data_fil <span class="ot">&lt;-</span> proc_data_fil <span class="sc">%&gt;%</span> </span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">confianza_insti =</span> <span class="fu">sum</span>(conf_cong, conf_gob, conf_partpol, conf_pres))</span>
<span id="cb136-4"><a href="#cb136-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data_fil<span class="sc">$</span>confianza_insti)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   1.000   3.000   3.599   6.000  16.000     214 </code></pre>
</div>
</div>
<p>Ya realizada la escala, obtenemos sus datos descriptivos. Entre los que podemos identificar que la media es de un 3.599 por lo que los casos tienden a centrarse en valores que poseen una muy baja percepcion con la confianza en la institucionalidad politica en instituciones como El Gobierno, El Congreso, Los Partidos Politicos y el Presidente de la Republica. Asimismo, se puede afiurmar que el rango de valores entre los que se encuentra la escala varian de 0 a 16.</p>
<p>A continuacion presentaremos un grafico mas interpretable para poder analizar en en mayor detalle nuestra escala generada.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(proc_data_fil, <span class="fu">aes</span>(<span class="at">x =</span> confianza_insti)) <span class="sc">+</span></span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.6</span>, <span class="at">colour=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"yellow"</span>) <span class="sc">+</span></span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb138-4"><a href="#cb138-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Confianza institucionalidad politica"</span>) <span class="sc">+</span></span>
<span id="cb138-5"><a href="#cb138-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Cantidad"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 214 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TRABAJO4RRRRRRR_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A partir de la construccion de la escala las variables de confianza en instituciones politicas de Congreso, Gobierno, Presidente de la Republica y Partidos Politicos, se demuetsra claramente que los casos tienden a concentrarse en la categoria de respuesta 0, mientras que segun los estadisticos descriptivos podemow observar que las categorias de respuestas tienden a concentrarse en mayor medida entre los valores 0 y 10, dejando de 10 a 15 muy pocos valores, lo que demuestra con creces la baja confianza en las instituciones politicas democraticas en personas jovenes de entre 18 a 30 años de edad.</p>
<p>Por ultimo, a modo de sintesis tambien es relevante afirmar que la forma en que se ejemplifica la figura del grafico adquiere estandares de valores que nos llevan a plantear que es un grafico asimetrico de caracter positivo, formando la suerte de una especie de -J de caracter invertido-.</p>
</section>
<section id="residuos" class="level3">
<h3 class="anchored" data-anchor-id="residuos">Residuos</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico x1 = ACT</span></span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>graph1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(proc_data_fil, <span class="fu">aes</span>(<span class="at">x =</span> edad_enc, <span class="at">y =</span> confianza_insti)) <span class="sc">+</span></span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Puntos</span></span>
<span id="cb140-4"><a href="#cb140-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>  <span class="co"># Recta de regresión</span></span>
<span id="cb140-5"><a href="#cb140-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Edad"</span>, <span class="at">y =</span> <span class="st">"Confianza institucional"</span>)  <span class="co"># Etiquetas de ejes</span></span>
<span id="cb140-6"><a href="#cb140-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-7"><a href="#cb140-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico 2</span></span>
<span id="cb140-8"><a href="#cb140-8" aria-hidden="true" tabindex="-1"></a>graph2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(proc_data_fil, <span class="fu">aes</span>(<span class="at">x =</span> actitud_demo, <span class="at">y =</span> confianza_insti)) <span class="sc">+</span></span>
<span id="cb140-9"><a href="#cb140-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb140-10"><a href="#cb140-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb140-11"><a href="#cb140-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Actitud democracia"</span>, <span class="at">y =</span> <span class="st">"Confianza institucional"</span>)</span>
<span id="cb140-12"><a href="#cb140-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-13"><a href="#cb140-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(graph1, graph2, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="co"># Unir graficos</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 214 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 214 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 233 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 233 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TRABAJO4RRRRRRR_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Con el gráfico anterior podemos notar que, si bien ambas variables tienen una asociación distinta con la confianza institucional, el tamaño efecto de esta relación es en parte distinto. Edad tiene una asociación levemente positiva, mientras que la postura de actitud frente a la democracia es incrementalmente (muy) positiva ya que va aumentando significativamente.</p>
</section>
<section id="regresion-lineal-simple" class="level3">
<h3 class="anchored" data-anchor-id="regresion-lineal-simple">Regresion lineal simple</h3>
<p>Aqui realizaremos una regresion lineal simple con la finalidad de poder moderla la relacion entre nuestras variables de estudio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(confianza_insti <span class="sc">~</span> edad_enc, <span class="at">data=</span>proc_data_fil)</span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(confianza_insti <span class="sc">~</span> sexo_enc, <span class="at">data=</span>proc_data_fil)</span>
<span id="cb147-3"><a href="#cb147-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-4"><a href="#cb147-4" aria-hidden="true" tabindex="-1"></a><span class="fu">knitreg</span>(<span class="fu">list</span>(reg2, reg3), </span>
<span id="cb147-5"><a href="#cb147-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.model.names =</span> <span class="fu">c</span>(<span class="st">"Modelo 1"</span>,</span>
<span id="cb147-6"><a href="#cb147-6" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Modelo 2"</span>),</span>
<span id="cb147-7"><a href="#cb147-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.note =</span> <span class="st">"*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05"</span>,</span>
<span id="cb147-8"><a href="#cb147-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.coef.names =</span> <span class="fu">c</span>(<span class="st">"Intercepto"</span>, </span>
<span id="cb147-9"><a href="#cb147-9" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Edad"</span>,</span>
<span id="cb147-10"><a href="#cb147-10" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Mujer &lt;br&gt; &lt;i&gt;(Ref. Hombre)&lt;/i&gt;"</span>), </span>
<span id="cb147-11"><a href="#cb147-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"Confianza Institucional"</span>,</span>
<span id="cb147-12"><a href="#cb147-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption.above =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;color: #000000;border-top: 2px solid #000000;"&gt;
&lt;caption&gt;Confianza Institucional&lt;/caption&gt;
&lt;thead&gt;
&lt;tr&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 1&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 2&lt;/th&gt;
&lt;/tr&gt;
&lt;/thead&gt;
&lt;tbody&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Intercepto&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;1.95&lt;sup&gt;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;3.53&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.92)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.42)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Edad&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.06&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.03)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Mujer &lt;br&gt; &lt;i&gt;(Ref. Hombre)&lt;/i&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.04&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.23)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Adj. R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.00&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-bottom: 2px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Num. obs.&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;1008&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;787&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;tfoot&gt;
&lt;tr&gt;
&lt;td style="font-size: 0.8em;" colspan="3"&gt;*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05&lt;/td&gt;
&lt;/tr&gt;
&lt;/tfoot&gt;
&lt;/table&gt;</code></pre>
</div>
</div>
<p>En el Modelo 1 se incluye edad como predictor, el cual tiene un coeficiente de regresión de 0,06. Esto indica que por cada unidad que aumenta edad, la confianza institucional aumenta en promedio 0,06 unidades aproximadamente. Dato que en cierta medida no es significativo por lo cual seria muy poco porbable el hecho de extrapolar estos datos a la población total. El intercepto es de 1,51, lo que indica que basandonos en una perspectiva teorica, una persona con edad 0 tendría un promedio de confianza institucional en los entes gubernamentales de 1,51. Finalmente, a grandes razgos se ppuede expresar que el modelo 1 logra explicar el 0% de la varianza de la variable dependiente (R2=0).</p>
<p>El Modelo 2 incluye la vaiable sexo, en donde el no tiene nivel de significancia. Al respecto, la mujer (ya que el hombre es sexo de referencia) con un valor que se aproxima a 0.02, tiene mayor nivel de confianza en las instituciones politicas gubernamentales en comparacion y respecto de los hombres.</p>
<p>Por tanto para finalizar se puede manifestar que en ambos modelos, se presenta un R cuadado ajustado de 0 sugiere que ambos modelos de regresión no explican ninguna de la variabilidad en la variable dependiente más allá de lo que se esperaría. En otras palabras, las variables independientes en los dos modelos trabajdados no proporcionan ninguna información útil para predecir la variable dependiente en sus respectivos casos.</p>
</section>
<section id="conclusiones-finales" class="level3">
<h3 class="anchored" data-anchor-id="conclusiones-finales">Conclusiones finales</h3>
<p>A grandes rasgos, se puede decir que la desconfianza en la institucionalidad política chilena, que incluye el Congreso, el gobierno y los partidos políticos, es un fenómeno complejo que refleja una serie de problemas arraigados en la sociedad. La literatura reciente, así como el trabajo realizado en el presente estudio, en parte afirma que se puede concluir que esta desconfianza surge de una combinación de factores, que van desde la percepción de corrupción y falta de transparencia hasta la desconexión entre los líderes políticos y las necesidades reales de la ciudadanía.</p>
<p>En donde las instituciones políticas en Chile enfrentan desafíos significativos en términos de legitimidad y representatividad. La falta de responsabilidad, la opacidad en la toma de decisiones y los escándalos de corrupción han erosionado la confianza de la población en sus líderes y en las instituciones que los respaldan. Por último, se hace relevante recalcar que la brecha entre las élites políticas y la ciudadanía común se ha ampliado, lo que ha generado un sentimiento de alienación y desapego hacia el sistema político generando una falta de interés. Y en donde en particular, los partidos políticos son percibidos como entidades distantes y desconectadas de las preocupaciones cotidianas de la gente, lo que ha contribuido a una creciente apatía y desinterés por la participación política.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>